// This file is auto-generated by @hey-api/openapi-ts

export const AccountMembershipPublicSchema = {
    properties: {
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        company_name: {
            type: 'string',
            title: 'Company Name'
        },
        role_id: {
            type: 'string',
            format: 'uuid',
            title: 'Role Id'
        },
        role_name: {
            type: 'string',
            title: 'Role Name'
        },
        role_display_name: {
            type: 'string',
            title: 'Role Display Name'
        },
        role_level: {
            type: 'integer',
            title: 'Role Level'
        },
        is_primary: {
            type: 'boolean',
            title: 'Is Primary'
        }
    },
    type: 'object',
    required: ['company_id', 'company_name', 'role_id', 'role_name', 'role_display_name', 'role_level', 'is_primary'],
    title: 'AccountMembershipPublic'
} as const;

export const AccountProfilePublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        memberships: {
            items: {
                '$ref': '#/components/schemas/AccountMembershipPublic'
            },
            type: 'array',
            title: 'Memberships'
        }
    },
    type: 'object',
    required: ['user_id', 'email', 'full_name', 'memberships'],
    title: 'AccountProfilePublic'
} as const;

export const AuditLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        actor_id: {
            type: 'string',
            format: 'uuid',
            title: 'Actor Id'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        entity_type: {
            type: 'string',
            title: 'Entity Type'
        },
        entity_id: {
            type: 'string',
            format: 'uuid',
            title: 'Entity Id'
        },
        old_value: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Old Value'
        },
        new_value: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'New Value'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'actor_id', 'action', 'entity_type', 'entity_id', 'old_value', 'new_value', 'created_at'],
    title: 'AuditLogPublic'
} as const;

export const Body_chat_upload_attachmentSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_chat-upload_attachment'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChatAttachmentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        message_id: {
            type: 'string',
            format: 'uuid',
            title: 'Message Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        mime_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mime Type'
        },
        size_bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size Bytes'
        },
        public_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public Url'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'message_id', 'filename', 'mime_type', 'size_bytes', 'public_url', 'created_at'],
    title: 'ChatAttachmentPublic',
    description: 'Chat attachment response.'
} as const;

export const ChatMemberAddSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        role: {
            type: 'string',
            enum: ['owner', 'admin', 'member'],
            title: 'Role',
            default: 'member'
        }
    },
    type: 'object',
    required: ['user_id'],
    title: 'ChatMemberAdd',
    description: 'Add a member to a room.'
} as const;

export const ChatMemberWithUserPublicSchema = {
    properties: {
        room_id: {
            type: 'string',
            format: 'uuid',
            title: 'Room Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        joined_at: {
            type: 'string',
            format: 'date-time',
            title: 'Joined At'
        },
        left_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Left At'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['room_id', 'user_id', 'role', 'joined_at', 'left_at', 'email'],
    title: 'ChatMemberWithUserPublic',
    description: 'Chat member response enriched with basic user info.'
} as const;

export const ChatMessageCreateSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'ChatMessageCreate',
    description: 'Create a message in a room (text only).'
} as const;

export const ChatMessagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        room_id: {
            type: 'string',
            format: 'uuid',
            title: 'Room Id'
        },
        sender_id: {
            type: 'string',
            format: 'uuid',
            title: 'Sender Id'
        },
        message_type: {
            type: 'string',
            title: 'Message Type'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'room_id', 'sender_id', 'message_type', 'content', 'created_at'],
    title: 'ChatMessagePublic',
    description: 'Chat message response.'
} as const;

export const ChatRoomCreateSchema = {
    properties: {
        room_type: {
            type: 'string',
            enum: ['direct', 'group'],
            title: 'Room Type',
            default: 'group'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        room_color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Color'
        },
        member_user_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Member User Ids'
        }
    },
    type: 'object',
    title: 'ChatRoomCreate',
    description: 'Create a chat room (direct/group).'
} as const;

export const ChatRoomPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        room_type: {
            type: 'string',
            title: 'Room Type'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        room_color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Color'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'company_id', 'room_type', 'name', 'room_color', 'created_by', 'created_at'],
    title: 'ChatRoomPublic',
    description: 'Chat room response.'
} as const;

export const ChatRoomUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        room_color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Color'
        }
    },
    type: 'object',
    title: 'ChatRoomUpdate',
    description: 'Update chat room fields (currently only name).'
} as const;

export const CompanyCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 100,
            title: 'Slug'
        }
    },
    type: 'object',
    required: ['name', 'slug'],
    title: 'CompanyCreate'
} as const;

export const CompanyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'name', 'slug', 'is_active'],
    title: 'CompanyPublic'
} as const;

export const CompanyUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'CompanyUpdate'
} as const;

export const DepartmentCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        dept_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dept Type'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DepartmentCreate'
} as const;

export const DepartmentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        dept_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dept Type'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'company_id', 'parent_id', 'name', 'dept_type', 'is_active'],
    title: 'DepartmentPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LogoutRequestSchema = {
    properties: {
        refresh_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Refresh Token'
        }
    },
    type: 'object',
    title: 'LogoutRequest'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OrgTreeDepartmentGroupPublicSchema = {
    properties: {
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        department_name: {
            type: 'string',
            title: 'Department Name'
        },
        roles: {
            items: {
                '$ref': '#/components/schemas/OrgTreeRoleNodePublic'
            },
            type: 'array',
            title: 'Roles'
        }
    },
    type: 'object',
    required: ['department_id', 'department_name', 'roles'],
    title: 'OrgTreeDepartmentGroupPublic'
} as const;

export const OrgTreeMemberPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        department_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Name'
        },
        is_current_user: {
            type: 'boolean',
            title: 'Is Current User',
            default: false
        }
    },
    type: 'object',
    required: ['user_id', 'full_name', 'email', 'department_id', 'department_name'],
    title: 'OrgTreeMemberPublic'
} as const;

export const OrgTreePublicSchema = {
    properties: {
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        company_name: {
            type: 'string',
            title: 'Company Name'
        },
        current_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Current User Id'
        },
        current_role_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Role Id'
        },
        current_role_level: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Role Level'
        },
        departments: {
            items: {
                '$ref': '#/components/schemas/OrgTreeDepartmentGroupPublic'
            },
            type: 'array',
            title: 'Departments'
        }
    },
    type: 'object',
    required: ['company_id', 'company_name', 'current_user_id', 'current_role_id', 'current_role_level', 'departments'],
    title: 'OrgTreePublic'
} as const;

export const OrgTreeRoleNodePublicSchema = {
    properties: {
        role_id: {
            type: 'string',
            format: 'uuid',
            title: 'Role Id'
        },
        role_name: {
            type: 'string',
            title: 'Role Name'
        },
        role_display_name: {
            type: 'string',
            title: 'Role Display Name'
        },
        role_level: {
            type: 'integer',
            title: 'Role Level'
        },
        relation_to_current: {
            type: 'string',
            title: 'Relation To Current'
        },
        members: {
            items: {
                '$ref': '#/components/schemas/OrgTreeMemberPublic'
            },
            type: 'array',
            title: 'Members'
        }
    },
    type: 'object',
    required: ['role_id', 'role_name', 'role_display_name', 'role_level', 'relation_to_current', 'members'],
    title: 'OrgTreeRoleNodePublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        code: {
            type: 'string',
            maxLength: 50,
            title: 'Code'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        status: {
            type: 'string',
            maxLength: 30,
            title: 'Status',
            default: 'planning'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        }
    },
    type: 'object',
    required: ['name', 'code', 'start_date', 'end_date'],
    title: 'ProjectCreate'
} as const;

export const ProjectPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        code: {
            type: 'string',
            maxLength: 50,
            title: 'Code'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        status: {
            type: 'string',
            maxLength: 30,
            title: 'Status',
            default: 'planning'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        pm_id: {
            type: 'string',
            format: 'uuid',
            title: 'Pm Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'code', 'start_date', 'end_date', 'id', 'company_id', 'department_id', 'pm_id', 'created_at', 'updated_at'],
    title: 'ProjectPublic'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        pm_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pm Id'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic'
} as const;

export const RefreshTokenRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['refresh_token'],
    title: 'RefreshTokenRequest'
} as const;

export const RoleSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        display_name: {
            type: 'string',
            maxLength: 100,
            title: 'Display Name'
        },
        level: {
            type: 'integer',
            title: 'Level',
            default: 3
        },
        is_system: {
            type: 'boolean',
            title: 'Is System',
            default: false
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        policy_doc: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Policy Doc'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['company_id', 'name', 'display_name'],
    title: 'Role',
    description: `Roles are DATA, not code.
System roles (is_system=True) are seeded and cannot be deleted.
Custom roles are created by admin via UI.`
} as const;

export const RoleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        level: {
            type: 'integer',
            title: 'Level',
            default: 3
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        policy_doc: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Policy Doc'
        }
    },
    type: 'object',
    required: ['name', 'display_name'],
    title: 'RoleCreate'
} as const;

export const RoleDependencyCreateSchema = {
    properties: {
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        from_role_id: {
            type: 'string',
            format: 'uuid',
            title: 'From Role Id'
        },
        to_role_id: {
            type: 'string',
            format: 'uuid',
            title: 'To Role Id'
        },
        relation_type: {
            type: 'string',
            enum: ['REPORTS_TO', 'PEERS_WITH', 'REQUIRES_APPROVAL_FROM'],
            title: 'Relation Type'
        }
    },
    type: 'object',
    required: ['company_id', 'from_role_id', 'to_role_id', 'relation_type'],
    title: 'RoleDependencyCreate'
} as const;

export const RoleDependencyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        from_role_id: {
            type: 'string',
            format: 'uuid',
            title: 'From Role Id'
        },
        from_role_name: {
            type: 'string',
            title: 'From Role Name'
        },
        to_role_id: {
            type: 'string',
            format: 'uuid',
            title: 'To Role Id'
        },
        to_role_name: {
            type: 'string',
            title: 'To Role Name'
        },
        relation_type: {
            type: 'string',
            title: 'Relation Type'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'company_id', 'from_role_id', 'from_role_name', 'to_role_id', 'to_role_name', 'relation_type', 'is_active', 'created_at'],
    title: 'RoleDependencyPublic'
} as const;

export const TaskCommentApprovalUpdateSchema = {
    properties: {
        approval_status: {
            type: 'string',
            enum: ['APPROVED', 'REJECTED'],
            title: 'Approval Status'
        }
    },
    type: 'object',
    required: ['approval_status'],
    title: 'TaskCommentApprovalUpdate'
} as const;

export const TaskCommentCreateSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        comment_type: {
            type: 'string',
            title: 'Comment Type',
            default: 'general'
        },
        requested_end_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested End Time'
        },
        approval_status: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['PENDING', 'APPROVED', 'REJECTED']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Approval Status'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'TaskCommentCreate'
} as const;

export const TaskCommentPublicSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        comment_type: {
            type: 'string',
            maxLength: 50,
            title: 'Comment Type',
            default: 'general'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        author_id: {
            type: 'string',
            format: 'uuid',
            title: 'Author Id'
        },
        author_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        is_edited: {
            type: 'boolean',
            title: 'Is Edited'
        },
        requested_end_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested End Time'
        },
        approval_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Approval Status'
        }
    },
    type: 'object',
    required: ['content', 'id', 'task_id', 'author_id', 'created_at', 'is_edited', 'requested_end_time', 'approval_status'],
    title: 'TaskCommentPublic'
} as const;

export const TaskCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 500,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        priority: {
            type: 'string',
            title: 'Priority',
            default: 'medium'
        },
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        end_time: {
            type: 'string',
            format: 'date-time',
            title: 'End Time'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        assignee_id: {
            type: 'string',
            format: 'uuid',
            title: 'Assignee Id'
        }
    },
    type: 'object',
    required: ['name', 'start_time', 'end_time', 'project_id', 'assignee_id'],
    title: 'TaskCreate'
} as const;

export const TaskDependencyCreateSchema = {
    properties: {
        blocking_task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Blocking Task Id'
        },
        dependent_task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Dependent Task Id'
        },
        dependency_type: {
            type: 'string',
            enum: ['FS', 'SS', 'FF', 'SF'],
            title: 'Dependency Type',
            default: 'FS'
        },
        lag_hours: {
            type: 'integer',
            title: 'Lag Hours',
            default: 0
        }
    },
    type: 'object',
    required: ['blocking_task_id', 'dependent_task_id'],
    title: 'TaskDependencyCreate'
} as const;

export const TaskLevelConfigCreateSchema = {
    properties: {
        level: {
            type: 'integer',
            title: 'Level'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        requires_proof: {
            type: 'boolean',
            title: 'Requires Proof',
            default: false
        },
        can_have_children: {
            type: 'boolean',
            title: 'Can Have Children',
            default: true
        },
        max_children: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Children'
        },
        assignable_role_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignable Role Ids'
        }
    },
    type: 'object',
    required: ['level', 'label'],
    title: 'TaskLevelConfigCreate'
} as const;

export const TaskLevelConfigPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        level: {
            type: 'integer',
            title: 'Level'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        requires_proof: {
            type: 'boolean',
            title: 'Requires Proof'
        },
        can_have_children: {
            type: 'boolean',
            title: 'Can Have Children'
        },
        max_children: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Children'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'level', 'label', 'requires_proof', 'can_have_children', 'max_children'],
    title: 'TaskLevelConfigPublic'
} as const;

export const TaskProgressReportCreateSchema = {
    properties: {
        photo_url: {
            type: 'string',
            maxLength: 1000,
            title: 'Photo Url'
        },
        progress_percent: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Progress Percent'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    required: ['photo_url', 'progress_percent'],
    title: 'TaskProgressReportCreate'
} as const;

export const TaskProgressReportPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        reporter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reporter Id'
        },
        reporter_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reporter Name'
        },
        photo_url: {
            type: 'string',
            title: 'Photo Url'
        },
        progress_percent: {
            type: 'integer',
            title: 'Progress Percent'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'task_id', 'reporter_id', 'photo_url', 'progress_percent', 'note', 'created_at'],
    title: 'TaskProgressReportPublic'
} as const;

export const TaskProofCreateSchema = {
    properties: {
        file_url: {
            type: 'string',
            title: 'File Url'
        },
        file_type: {
            type: 'string',
            title: 'File Type',
            default: 'image'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        gps_lat: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gps Lat'
        },
        gps_lng: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gps Lng'
        },
        captured_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Captured At'
        },
        device_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Info'
        }
    },
    type: 'object',
    required: ['file_url'],
    title: 'TaskProofCreate'
} as const;

export const TaskProofPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        uploader_id: {
            type: 'string',
            format: 'uuid',
            title: 'Uploader Id'
        },
        file_url: {
            type: 'string',
            title: 'File Url'
        },
        file_type: {
            type: 'string',
            title: 'File Type'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        gps_lat: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gps Lat'
        },
        gps_lng: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gps Lng'
        },
        review_status: {
            type: 'string',
            title: 'Review Status'
        },
        reviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewer Id'
        },
        uploaded_at: {
            type: 'string',
            format: 'date-time',
            title: 'Uploaded At'
        }
    },
    type: 'object',
    required: ['id', 'task_id', 'uploader_id', 'file_url', 'file_type', 'note', 'gps_lat', 'gps_lng', 'review_status', 'reviewer_id', 'uploaded_at'],
    title: 'TaskProofPublic'
} as const;

export const TaskPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 500,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        priority: {
            type: 'string',
            maxLength: 20,
            title: 'Priority',
            default: 'medium'
        },
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        end_time: {
            type: 'string',
            format: 'date-time',
            title: 'End Time'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        level: {
            type: 'integer',
            title: 'Level'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        computed_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Computed Status'
        },
        assignor_id: {
            type: 'string',
            format: 'uuid',
            title: 'Assignor Id'
        },
        assignee_id: {
            type: 'string',
            format: 'uuid',
            title: 'Assignee Id'
        },
        actual_end_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual End Time'
        },
        is_on_critical_path: {
            type: 'boolean',
            title: 'Is On Critical Path'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        reported_progress_total: {
            type: 'integer',
            title: 'Reported Progress Total',
            default: 0
        }
    },
    type: 'object',
    required: ['name', 'start_time', 'end_time', 'id', 'project_id', 'parent_id', 'level', 'status', 'assignor_id', 'assignee_id', 'actual_end_time', 'is_on_critical_path', 'created_at', 'updated_at'],
    title: 'TaskPublic'
} as const;

export const TaskStatusUpdateSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'TaskStatusUpdate'
} as const;

export const TaskUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        priority: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        start_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        }
    },
    type: 'object',
    title: 'TaskUpdate'
} as const;

export const TasksPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TaskPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TasksPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        refresh_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Refresh Token'
        },
        session_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Session Id'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCompanyRoleCreateSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        role_id: {
            type: 'string',
            format: 'uuid',
            title: 'Role Id'
        },
        is_primary: {
            type: 'boolean',
            title: 'Is Primary',
            default: false
        }
    },
    type: 'object',
    required: ['user_id', 'company_id', 'role_id'],
    title: 'UserCompanyRoleCreate'
} as const;

export const UserCompanyRolePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        role_id: {
            type: 'string',
            format: 'uuid',
            title: 'Role Id'
        },
        role_name: {
            type: 'string',
            title: 'Role Name'
        },
        role_display_name: {
            type: 'string',
            title: 'Role Display Name'
        },
        company_name: {
            type: 'string',
            title: 'Company Name'
        },
        is_primary: {
            type: 'boolean',
            title: 'Is Primary'
        },
        assigned_at: {
            type: 'string',
            format: 'date-time',
            title: 'Assigned At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'company_id', 'role_id', 'role_name', 'role_display_name', 'company_name', 'is_primary', 'assigned_at'],
    title: 'UserCompanyRolePublic'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        job_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Title'
        },
        availability_status: {
            type: 'string',
            title: 'Availability Status',
            default: 'free'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;