// This file is auto-generated by @hey-api/openapi-ts

export type _AdjustHoursRequest = {
    work_hours: number;
    note?: (string | null);
};

export type _ParticipantApproveRequest = {
    note?: (string | null);
};

export type AccountMembershipPublic = {
    company_id: string;
    company_name: string;
    role_id: string;
    role_name: string;
    role_display_name: string;
    role_level: number;
    is_primary: boolean;
};

export type AccountProfilePublic = {
    user_id: string;
    email: string;
    full_name: (string | null);
    memberships: Array<AccountMembershipPublic>;
};

export type AdminUserActivityRow = {
    at: string;
    type: string;
    ip_address: (string | null);
    user_agent: (string | null);
};

export type AdminUserDetail = {
    id: string;
    email: string;
    full_name: (string | null);
    is_active: boolean;
    is_superuser: boolean;
    job_title: (string | null);
    availability_status: string;
    company_id: (string | null);
    company_name: (string | null);
    department_id: (string | null);
    department_name: (string | null);
    created_at: (string | null);
    memberships: Array<AdminUserMembership>;
    active_sessions: Array<AdminUserSessionInfo>;
    recent_activity: Array<AdminUserActivityRow>;
};

export type AdminUserListRow = {
    id: string;
    email: string;
    full_name: (string | null);
    is_active: boolean;
    is_superuser: boolean;
    company_id: (string | null);
    company_name: (string | null);
    department_id: (string | null);
    department_name: (string | null);
    primary_role_id: (string | null);
    primary_role_name: (string | null);
    primary_role_display_name: (string | null);
    primary_role_level: (number | null);
    last_login_at: (string | null);
    created_at: (string | null);
};

export type AdminUserMembership = {
    company_id: string;
    company_name: string;
    role_id: string;
    role_name: string;
    role_display_name: string;
    role_level: number;
    is_primary: boolean;
    assigned_at: (string | null);
};

export type AdminUserSessionInfo = {
    session_id: string;
    login_at: (string | null);
    last_seen_at: (string | null);
    ip_address: (string | null);
    user_agent: (string | null);
};

export type ApplyProfileRequest = {
    project_id: string;
    parent_task_id?: (string | null);
    assignee_id: string;
    extra_assignee_ids?: Array<(string)>;
};

export type AttendanceRecordPublic = {
    id: string;
    user_id: string;
    mode: string;
    project_id: (string | null);
    company_id: (string | null);
    customer_company_id: (string | null);
    task_label: (string | null);
    work_date: string;
    check_in_at: string;
    check_in_lat: number;
    check_in_lng: number;
    check_in_accuracy_m: (number | null);
    check_in_distance_m: number;
    check_in_valid: boolean;
    check_in_photo_url: string;
    check_out_at: (string | null);
    check_out_lat: (number | null);
    check_out_lng: (number | null);
    check_out_accuracy_m: (number | null);
    check_out_distance_m: (number | null);
    check_out_valid: (boolean | null);
    check_out_photo_url: (string | null);
    work_hours: (number | null);
    is_capped: boolean;
    is_auto_closed: boolean;
    note: (string | null);
    created_at: string;
};

export type AttendanceRecordsPublic = {
    data: Array<AttendanceRecordPublic>;
    count: number;
};

export type AuditLogPublic = {
    id: string;
    actor_id?: (string | null);
    actor_name?: (string | null);
    action: string;
    entity_type: string;
    entity_id: string;
    old_value: (unknown | null);
    new_value: (unknown | null);
    created_at: string;
};

/**
 * Minimal info about a task that is blocking this one.
 */
export type BlockerInfo = {
    id: string;
    name: string;
    status: string;
};

export type Body_attendance_check_in = {
    file: (Blob | File);
    lat: number;
    lng: number;
    mode?: string;
    project_id?: (string | null);
    company_id?: (string | null);
    customer_company_id?: (string | null);
    task_label?: (string | null);
    accuracy_m?: (number | null);
    note?: (string | null);
};

export type Body_attendance_check_out = {
    file: (Blob | File);
    record_id: string;
    lat: number;
    lng: number;
    accuracy_m?: (number | null);
};

export type Body_chat_upload_attachment = {
    file: (Blob | File);
};

export type Body_contracts_upload_attachment = {
    file: (Blob | File);
};

export type Body_incidents_add_incident_attachment = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_quotations_upload_attachment_file = {
    file: (Blob | File);
};

export type Body_tasks_add_progress_report = {
    file: (Blob | File);
    progress_percent: number;
    note?: (string | null);
    gps_lat?: (number | null);
    gps_lng?: (number | null);
    gps_accuracy_m?: (number | null);
    checkin_skip_reason?: (string | null);
};

export type Body_tasks_upload_progress_report_photo = {
    file: (Blob | File);
};

/**
 * Chat attachment response.
 */
export type ChatAttachmentPublic = {
    id: string;
    message_id: string;
    filename: string;
    mime_type: (string | null);
    size_bytes: (number | null);
    public_url: (string | null);
    created_at: string;
};

/**
 * Add a member to a room.
 */
export type ChatMemberAdd = {
    user_id: string;
    role?: 'owner' | 'admin' | 'member';
};

export type role = 'owner' | 'admin' | 'member';

/**
 * Chat member response enriched with basic user info.
 */
export type ChatMemberWithUserPublic = {
    room_id: string;
    user_id: string;
    role: string;
    joined_at: string;
    left_at: (string | null);
    email: string;
    full_name?: (string | null);
};

/**
 * Create a message in a room (text only).
 */
export type ChatMessageCreate = {
    content: string;
};

/**
 * Chat message response.
 */
export type ChatMessagePublic = {
    id: string;
    room_id: string;
    sender_id: string;
    message_type: string;
    content: (string | null);
    created_at: string;
};

/**
 * Create a chat room (direct/group).
 */
export type ChatRoomCreate = {
    room_type?: 'direct' | 'group';
    name?: (string | null);
    room_color?: (string | null);
    member_user_ids?: Array<(string)>;
};

export type room_type = 'direct' | 'group';

/**
 * Chat room response.
 */
export type ChatRoomPublic = {
    id: string;
    company_id: string;
    room_type: string;
    name: (string | null);
    room_color: (string | null);
    created_by: string;
    created_at: string;
    last_message_content?: (string | null);
    last_message_at?: (string | null);
};

/**
 * Update chat room fields (currently only name).
 */
export type ChatRoomUpdate = {
    name?: (string | null);
    room_color?: (string | null);
};

/**
 * Total unread message count across all rooms.
 */
export type ChatUnreadCountPublic = {
    count: number;
};

export type CompanyCreate = {
    name: string;
    slug: string;
};

/**
 * Member projection for company management UI.
 */
export type CompanyMemberPublic = {
    user_id: string;
    email: string;
    full_name: (string | null);
    role_id: string;
    role_name: string;
    role_display_name: string;
    role_level: number;
    is_primary: boolean;
    department_id?: (string | null);
};

/**
 * Payload to update company member role assignment.
 */
export type CompanyMemberRoleUpdateRequest = {
    current_role_id: string;
    new_role_id: string;
    is_primary?: boolean;
};

export type CompanyPublic = {
    id: string;
    name: string;
    slug: string;
    is_active: boolean;
    site_lat?: (number | null);
    site_lng?: (number | null);
    site_radius_m?: number;
};

export type CompanyUpdate = {
    name?: (string | null);
    is_active?: (boolean | null);
};

export type ContractActionRequest = {
    note?: (string | null);
};

export type ContractAttachmentPublic = {
    id: string;
    contract_id: string;
    uploaded_by: string;
    file_url: string;
    file_name: string;
    file_type: string;
    phase: (string | null);
    description: (string | null);
    uploaded_at: string;
};

export type ContractConfirmAdvanceRequest = {
    advance_amount: number;
    advance_paid_at: string;
    note?: (string | null);
};

export type ContractCreate = {
    contract_date: string;
    total_value: number;
    currency?: string;
    advance_amount?: (number | null);
    notes?: (string | null);
    quotation_id: string;
    project_id?: (string | null);
};

export type ContractPublic = {
    contract_date: string;
    total_value: number;
    currency?: string;
    advance_amount?: (number | null);
    notes?: (string | null);
    id: string;
    company_id: string;
    quotation_id: string;
    project_id: (string | null);
    contract_number: string;
    signing_date: (string | null);
    status: string;
    status_label?: (string | null);
    advance_paid_at: (string | null);
    advance_paid_by: (string | null);
    created_by: string;
    created_at: string;
    updated_at: string;
};

export type ContractSignRequest = {
    signing_date: string;
    note?: (string | null);
};

export type ContractsPublic = {
    data: Array<ContractPublic>;
    count: number;
};

export type ContractStatusTransitionPublic = {
    id: string;
    contract_id: string;
    from_status: (string | null);
    to_status: string;
    actor_id: string;
    actor_name: (string | null);
    action: string;
    note: (string | null);
    created_at: string;
};

export type ContractUpdate = {
    contract_date?: (string | null);
    total_value?: (number | null);
    currency?: (string | null);
    advance_amount?: (number | null);
    notes?: (string | null);
    signing_date?: (string | null);
};

export type ContractWithDetailsPublic = {
    contract_date: string;
    total_value: number;
    currency?: string;
    advance_amount?: (number | null);
    notes?: (string | null);
    id: string;
    company_id: string;
    quotation_id: string;
    project_id: (string | null);
    contract_number: string;
    signing_date: (string | null);
    status: string;
    status_label?: (string | null);
    advance_paid_at: (string | null);
    advance_paid_by: (string | null);
    created_by: string;
    created_at: string;
    updated_at: string;
    attachments?: Array<ContractAttachmentPublic>;
    transitions?: Array<ContractStatusTransitionPublic>;
};

export type CustomerCompaniesPublic = {
    data: Array<CustomerCompanyPublic>;
    count: number;
};

export type CustomerCompanyCreate = {
    name: string;
    type?: string;
    tax_code?: (string | null);
    contact_name?: (string | null);
    contact_title?: (string | null);
    contact_phone?: (string | null);
    contact_email?: (string | null);
    address?: (string | null);
    notes?: (string | null);
    site_lat?: (number | null);
    site_lng?: (number | null);
    site_radius_m?: number;
};

export type CustomerCompanyPublic = {
    name: string;
    type?: string;
    tax_code?: (string | null);
    contact_name?: (string | null);
    contact_title?: (string | null);
    contact_phone?: (string | null);
    contact_email?: (string | null);
    address?: (string | null);
    notes?: (string | null);
    site_lat?: (number | null);
    site_lng?: (number | null);
    site_radius_m?: number;
    id: string;
    company_id: string;
    is_active: boolean;
    created_by: string;
    created_at: string;
    updated_at: string;
};

export type CustomerCompanyUpdate = {
    name?: (string | null);
    type?: (string | null);
    tax_code?: (string | null);
    contact_name?: (string | null);
    contact_title?: (string | null);
    contact_phone?: (string | null);
    contact_email?: (string | null);
    address?: (string | null);
    notes?: (string | null);
    site_lat?: (number | null);
    site_lng?: (number | null);
    site_radius_m?: (number | null);
    is_active?: (boolean | null);
};

export type DelayWarningPublic = {
    severity: string;
    layer: number;
    title: string;
    detail: string;
    task_id?: (string | null);
    task_name?: (string | null);
    estimated_delay_days?: (number | null);
};

export type DelayWarningsPublic = {
    warnings: Array<DelayWarningPublic>;
    analyzed_at: string;
};

export type DepartmentCreate = {
    name: string;
    parent_id?: (string | null);
    dept_type?: (string | null);
};

export type DepartmentPublic = {
    id: string;
    company_id: string;
    parent_id: (string | null);
    name: string;
    dept_type: (string | null);
    is_active: boolean;
};

export type DepartmentUpdate = {
    name?: (string | null);
    dept_type?: (string | null);
    is_active?: (boolean | null);
    parent_id?: (string | null);
};

/**
 * Response schema for a task dependency link.
 */
export type DependencyPublic = {
    id: string;
    blocking_task_id: string;
    dependent_task_id: string;
    dependency_type: string;
    lag_hours: number;
};

/**
 * Response schema for the project Gantt endpoint.
 */
export type GanttPublic = {
    tasks: Array<TaskPublic>;
    dependencies: Array<DependencyPublic>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IncidentAttachmentPublic = {
    id: string;
    file_url: string;
    file_type: string;
    uploaded_at: string;
};

export type IncidentCreate = {
    title: string;
    description: string;
    category?: string;
    severity?: string;
    project_id?: (string | null);
    task_id?: (string | null);
    root_cause?: (string | null);
    solution?: (string | null);
};

export type IncidentPublic = {
    id: string;
    company_id: string;
    project_id: (string | null);
    task_id: (string | null);
    title: string;
    description: string;
    category: string;
    severity: string;
    root_cause: (string | null);
    solution: (string | null);
    status: string;
    reported_by: string;
    resolved_by: (string | null);
    resolved_at: (string | null);
    created_at: string;
    updated_at: string;
    attachments?: Array<IncidentAttachmentPublic>;
};

export type IncidentResolve = {
    root_cause: string;
    solution: string;
};

export type IncidentsPublic = {
    data: Array<IncidentPublic>;
    count: number;
};

export type IncidentUpdate = {
    title?: (string | null);
    description?: (string | null);
    category?: (string | null);
    severity?: (string | null);
    root_cause?: (string | null);
    solution?: (string | null);
};

/**
 * One configured approver step (input).
 */
export type LeaveApproverConfigItem = {
    step_order?: number;
    approver_role_id?: (string | null);
    approver_user_id?: (string | null);
};

/**
 * The configured chain plus whether the default (directors) is in effect.
 */
export type LeaveApproverConfigListPublic = {
    data: Array<LeaveApproverConfigPublic>;
    uses_default: boolean;
};

export type LeaveApproverConfigPublic = {
    id: string;
    step_order: number;
    approver_role_id: (string | null);
    approver_user_id: (string | null);
    is_active: boolean;
    approver_role_name?: (string | null);
    approver_user_name?: (string | null);
};

/**
 * Replace the whole approver chain for a company.
 */
export type LeaveApproverConfigUpdate = {
    items: Array<LeaveApproverConfigItem>;
};

/**
 * Body for approve / reject. `note` is required when rejecting.
 */
export type LeaveDecisionRequest = {
    note?: (string | null);
};

export type LeaveRequestCreate = {
    leave_type?: string;
    start_date: string;
    end_date: string;
    half_day?: (string | null);
    reason?: (string | null);
};

export type LeaveRequestPublic = {
    id: string;
    company_id: string;
    user_id: string;
    leave_type: string;
    start_date: string;
    end_date: string;
    half_day: (string | null);
    num_days: number;
    reason: (string | null);
    status: string;
    decided_by: (string | null);
    decided_at: (string | null);
    decision_note: (string | null);
    created_at: string;
    user_name?: (string | null);
    decided_by_name?: (string | null);
};

export type LeaveRequestsPublic = {
    data: Array<LeaveRequestPublic>;
    count: number;
};

export type LogoutRequest = {
    refresh_token?: (string | null);
};

export type MembershipCreate = {
    company_id: string;
    role_id: string;
    department_id?: (string | null);
    is_primary?: boolean;
};

export type MembershipUpdate = {
    role_id?: (string | null);
    department_id?: (string | null);
    clear_department?: boolean;
    is_primary?: (boolean | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Response schema for a notification.
 */
export type NotificationPublic = {
    id: string;
    user_id: string;
    type: string;
    title: string;
    body: (string | null);
    entity_type: string;
    entity_id: string;
    is_read: boolean;
    created_at: string;
};

/**
 * Response schema for unread notification count.
 */
export type NotificationUnreadCount = {
    count: number;
};

export type OrgTreeDepartmentGroupPublic = {
    department_id: (string | null);
    department_name: string;
    roles: Array<OrgTreeRoleNodePublic>;
};

export type OrgTreeMemberPublic = {
    user_id: string;
    full_name: (string | null);
    email: string;
    department_id: (string | null);
    department_name: (string | null);
    is_current_user?: boolean;
};

export type OrgTreePublic = {
    company_id: string;
    company_name: string;
    current_user_id: string;
    current_role_id: (string | null);
    current_role_level: (number | null);
    departments: Array<OrgTreeDepartmentGroupPublic>;
};

export type OrgTreeRoleNodePublic = {
    role_id: string;
    role_name: string;
    role_display_name: string;
    role_level: number;
    relation_to_current: string;
    members: Array<OrgTreeMemberPublic>;
};

export type PermissionItem = {
    code: string;
    module: string;
    action: string;
    scope: string;
    description: string;
};

export type PermissionPublic = {
    id: string;
    code: string;
    module: string;
    action: string;
    scope: string;
    description: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    name: string;
    code: string;
    description?: (string | null);
    start_date: string;
    end_date: string;
    status?: string;
    project_type?: string;
    department_id?: (string | null);
    company_id?: (string | null);
    pm_id?: (string | null);
};

/**
 * Project membership with resolved user and role labels for API clients.
 */
export type ProjectMemberWithUserPublic = {
    user_id: string;
    role_id: string;
    joined_at: string;
    full_name?: (string | null);
    email: string;
    role_display_name: string;
};

export type ProjectPublic = {
    name: string;
    code: string;
    description?: (string | null);
    start_date: string;
    end_date: string;
    status?: string;
    project_type?: string;
    id: string;
    company_id: string;
    department_id: (string | null);
    pm_id: string;
    chat_room_id?: (string | null);
    site_lat?: (number | null);
    site_lng?: (number | null);
    site_radius_m?: number;
    created_at: string;
    updated_at: string;
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    name?: (string | null);
    description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    status?: (string | null);
    pm_id?: (string | null);
    project_type?: (string | null);
};

export type PushSubscribeRequest = {
    endpoint: string;
    p256dh: string;
    auth: string;
};

export type QuotationApprovalParticipantCreate = {
    user_id: string;
    role: string;
};

export type QuotationApprovalParticipantPublic = {
    id: string;
    quotation_id: string;
    stage: string;
    user_id: string;
    user_name?: (string | null);
    role: string;
    has_approved: boolean;
    approved_at: (string | null);
    created_at: string;
};

/**
 * BGĐ approve or reject a stage (S2, S4, S7, S8B).
 * When action=reject, target_stage overrides the default reject destination.
 */
export type QuotationApproveRequest = {
    action: 'approve' | 'reject';
    note?: (string | null);
    target_stage?: (string | null);
};

export type action = 'approve' | 'reject';

export type QuotationAttachmentCreate = {
    file_url: string;
    file_name: string;
    file_type?: string;
    document_category?: string;
    description?: (string | null);
};

export type QuotationAttachmentPublic = {
    id: string;
    quotation_id: string;
    uploaded_by: string;
    uploaded_by_name?: (string | null);
    file_url: string;
    file_name: string;
    file_type: string;
    document_category: string;
    stage_uploaded: string;
    description: (string | null);
    uploaded_at: string;
};

export type QuotationByClientRow = {
    client_company_name: string;
    total: number;
    won: number;
    lost: number;
    in_progress: number;
    win_rate: (number | null);
    total_won_value: (number | null);
};

export type QuotationByEquipmentRow = {
    equipment_category: string;
    total: number;
    won: number;
    lost: number;
    win_rate: (number | null);
};

/**
 * S8 → S9: KD đóng hồ sơ.
 */
export type QuotationCloseRequest = {
    outcome: 'won' | 'lost';
    lost_reason_category?: (string | null);
    lost_reason_detail?: (string | null);
    note?: (string | null);
    extra_role_ids?: (Array<(string)> | null);
};

export type outcome = 'won' | 'lost';

/**
 * Latest remembered client-company info for quotation creation.
 */
export type QuotationCompanyProfilePublic = {
    client_company_name: string;
    client_contact_name?: (string | null);
    client_contact_title?: (string | null);
    client_contact_phone?: (string | null);
    client_contact_email?: (string | null);
    client_address?: (string | null);
    notes?: (string | null);
    survey_note?: (string | null);
    equipment_category?: (string | null);
};

/**
 * Fields required to open a new quotation (Kinh Doanh).
 */
export type QuotationCreate = {
    project_name: string;
    client_company_id?: (string | null);
    client_company_name: string;
    client_contact_name?: (string | null);
    client_contact_title?: (string | null);
    client_contact_phone?: (string | null);
    client_contact_email?: (string | null);
    client_address?: (string | null);
    equipment_category?: (string | null);
    notes?: (string | null);
    survey_note?: (string | null);
    color?: (string | null);
    sales_owner_id?: (string | null);
};

/**
 * S6 → S7: KD hoàn thiện hợp đồng chào giá (upload file + điều khoản), nộp GĐ duyệt.
 */
export type QuotationFinalizeRequest = {
    note?: (string | null);
};

export type QuotationLostReasonRow = {
    lost_reason_category: string;
    count: number;
    percentage: number;
};

export type QuotationNegotiationLogCreate = {
    contact_date: string;
    contact_method: string;
    summary: string;
    client_feedback?: (string | null);
    requested_changes?: (string | null);
    follow_up_date?: (string | null);
    attachments?: (Array<(string)> | null);
};

export type QuotationNegotiationLogPublic = {
    contact_date: string;
    contact_method: string;
    summary: string;
    client_feedback?: (string | null);
    requested_changes?: (string | null);
    follow_up_date?: (string | null);
    id: string;
    quotation_id: string;
    logged_by: string;
    logged_by_name?: (string | null);
    attachments: (Array<(string)> | null);
    created_at: string;
};

export type QuotationPublic = {
    project_name: string;
    client_company_id?: (string | null);
    client_company_name: string;
    client_contact_name?: (string | null);
    client_contact_title?: (string | null);
    client_contact_phone?: (string | null);
    client_contact_email?: (string | null);
    client_address?: (string | null);
    equipment_category?: (string | null);
    notes?: (string | null);
    survey_note?: (string | null);
    color?: (string | null);
    id: string;
    company_id: string;
    quote_number: string;
    status: string;
    current_stage: string;
    stage_label?: (string | null);
    site_survey_date: (string | null);
    survey_start_date: (string | null);
    survey_end_date: (string | null);
    created_by: string;
    sales_owner_id: string;
    sales_owner_name?: (string | null);
    technical_owner_id: (string | null);
    technical_owner_name?: (string | null);
    procurement_owner_id: (string | null);
    procurement_owner_name?: (string | null);
    total_contract_value: (number | null);
    currency: string;
    valid_until: (string | null);
    sent_to_client_at: (string | null);
    client_response_deadline: (string | null);
    outcome: (string | null);
    lost_reason_category: (string | null);
    lost_reason_detail: (string | null);
    won_project_id: (string | null);
    created_at: string;
    updated_at: string;
};

export type QuotationReportSummary = {
    total: number;
    in_progress: number;
    sent: number;
    negotiating: number;
    closed_won: number;
    closed_lost: number;
    win_rate: (number | null);
    total_won_value: (number | null);
    period_from: (string | null);
    period_to: (string | null);
};

/**
 * S8: KD ghi nhận đã gửi khách hàng.
 */
export type QuotationSendToClientRequest = {
    valid_until?: (string | null);
    client_response_deadline?: (string | null);
    note?: (string | null);
};

export type QuotationsPublic = {
    data: Array<QuotationPublic>;
    count: number;
};

export type QuotationStageTransitionPublic = {
    id: string;
    quotation_id: string;
    from_stage: (string | null);
    from_stage_label?: (string | null);
    to_stage: string;
    to_stage_label?: (string | null);
    actor_id: string;
    actor_name?: (string | null);
    action: string;
    action_label?: (string | null);
    note: (string | null);
    created_at: string;
};

/**
 * S3B: KT hoàn thành bóc tách khối lượng → S4.
 */
export type QuotationSubmitBocTachRequest = {
    note?: (string | null);
};

/**
 * S3 → S4: KT nộp thiết kế.
 */
export type QuotationSubmitDesignRequest = {
    note?: (string | null);
};

/**
 * S8 → S8B: KD ghi nhận thương lượng và trình GĐ duyệt.
 */
export type QuotationSubmitNegotiationRequest = {
    note: string;
};

/**
 * S5 → S6: VT upload file báo giá đã điền giá, nhập tổng giá trị hợp đồng.
 */
export type QuotationSubmitPricingRequest = {
    total_contract_value: number;
    note?: (string | null);
};

/**
 * S1 → S2: KD nộp báo cáo khảo sát.
 */
export type QuotationSubmitSurveyRequest = {
    client_contact_name?: (string | null);
    client_contact_phone?: (string | null);
    client_contact_title?: (string | null);
    client_address?: (string | null);
    site_survey_date?: (string | null);
    survey_start_date?: (string | null);
    survey_end_date?: (string | null);
    note?: (string | null);
};

export type QuotationUpdate = {
    project_name?: (string | null);
    client_company_id?: (string | null);
    client_company_name?: (string | null);
    client_contact_name?: (string | null);
    client_contact_title?: (string | null);
    client_contact_phone?: (string | null);
    client_contact_email?: (string | null);
    client_address?: (string | null);
    equipment_category?: (string | null);
    notes?: (string | null);
    survey_note?: (string | null);
    site_survey_date?: (string | null);
    survey_start_date?: (string | null);
    survey_end_date?: (string | null);
    valid_until?: (string | null);
    client_response_deadline?: (string | null);
    technical_owner_id?: (string | null);
    procurement_owner_id?: (string | null);
    color?: (string | null);
};

export type QuotationVersionPublic = {
    id: string;
    quotation_id: string;
    version_number: number;
    snapshot_data: unknown;
    created_by: string;
    created_by_name?: (string | null);
    reason: (string | null);
    created_at: string;
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

/**
 * Roles are DATA, not code.
 * System roles (is_system=True) are seeded and cannot be deleted.
 * Custom roles are created by admin via UI.
 */
export type Role = {
    id?: string;
    company_id: string;
    name: string;
    display_name: string;
    level?: number;
    is_system?: boolean;
    description?: (string | null);
    policy_doc?: ({
    [key: string]: unknown;
} | null);
    created_at?: string;
};

export type RoleCreate = {
    name: string;
    display_name: string;
    level?: number;
    description?: (string | null);
    policy_doc?: ({
    [key: string]: unknown;
} | null);
};

export type RoleDependencyCreate = {
    company_id: string;
    from_role_id: string;
    to_role_id: string;
    relation_type: 'REPORTS_TO' | 'PEERS_WITH' | 'REQUIRES_APPROVAL_FROM';
};

export type relation_type = 'REPORTS_TO' | 'PEERS_WITH' | 'REQUIRES_APPROVAL_FROM';

export type RoleDependencyPublic = {
    id: string;
    company_id: string;
    from_role_id: string;
    from_role_name: string;
    to_role_id: string;
    to_role_name: string;
    relation_type: string;
    is_active: boolean;
    created_at: string;
};

/**
 * Payload to replace a role's permission set.
 */
export type RolePermissionAssignRequest = {
    permission_codes: Array<(string)>;
};

/**
 * Result of role permission assignment.
 */
export type RolePermissionAssignResponse = {
    role_id: string;
    assigned_permission_codes: Array<(string)>;
};

export type SaveAsProfileRequest = {
    name: string;
    description?: (string | null);
    company_id?: (string | null);
};

/**
 * Set/clear a project's site coordinates and allowed radius.
 */
export type SiteLocationUpdate = {
    site_lat?: (number | null);
    site_lng?: (number | null);
    site_radius_m?: (number | null);
};

export type TaskAssigneeAdd = {
    user_id: string;
};

export type TaskAssigneePublic = {
    id: string;
    task_id: string;
    user_id: string;
    user_name?: (string | null);
    assigned_by: string;
    assigned_at: string;
};

export type TaskCommentApprovalUpdate = {
    approval_status: 'APPROVED' | 'REJECTED';
};

export type approval_status = 'APPROVED' | 'REJECTED';

export type TaskCommentCreate = {
    content: string;
    comment_type?: string;
    requested_end_time?: (string | null);
    approval_status?: ('PENDING' | 'APPROVED' | 'REJECTED' | null);
};

export type TaskCommentPublic = {
    content: string;
    comment_type?: string;
    id: string;
    task_id: string;
    author_id: string;
    author_name?: (string | null);
    created_at: string;
    is_edited: boolean;
    requested_end_time: (string | null);
    approval_status: (string | null);
};

export type TaskCreate = {
    name: string;
    description?: (string | null);
    priority?: string;
    start_time: string;
    end_time: string;
    project_id: string;
    parent_id?: (string | null);
    assignee_id: string;
    extra_assignee_ids?: Array<(string)>;
    progress_weight?: (number | null);
    module_tag?: (string | null);
    linked_entity_type?: (string | null);
    linked_entity_id?: (string | null);
    requires_checkin?: boolean;
    checkin_lat?: (number | null);
    checkin_lng?: (number | null);
    checkin_radius_m?: (number | null);
};

export type TaskDependencyCreate = {
    blocking_task_id: string;
    dependent_task_id: string;
    dependency_type?: 'FS' | 'SS' | 'FF' | 'SF';
    lag_hours?: number;
};

export type dependency_type = 'FS' | 'SS' | 'FF' | 'SF';

export type TaskLevelConfigCreate = {
    level: number;
    label: string;
    requires_proof?: boolean;
    can_have_children?: boolean;
    max_children?: (number | null);
    assignable_role_ids?: (Array<(string)> | null);
};

export type TaskLevelConfigPublic = {
    id: string;
    project_id: string;
    level: number;
    label: string;
    requires_proof: boolean;
    can_have_children: boolean;
    max_children: (number | null);
};

export type TaskLinkedEntityPublic = {
    id: string;
    task_id: string;
    entity_type: string;
    entity_id: string;
    created_by: string;
    created_at: string;
};

export type TaskObserverAdd = {
    user_id: string;
};

export type TaskObserverPublic = {
    task_id: string;
    user_id: string;
    user_name?: (string | null);
    added_at: string;
};

export type TaskProfileCreate = {
    name: string;
    description?: (string | null);
    company_id?: (string | null);
};

export type TaskProfileItemCreate = {
    parent_item_id?: (string | null);
    name: string;
    duration_days?: number;
    order_index?: number;
    description?: (string | null);
    module_tag?: (string | null);
    color?: (string | null);
};

export type TaskProfileItemPublic = {
    id: string;
    profile_id: string;
    parent_item_id: (string | null);
    name: string;
    level: number;
    duration_days: number;
    order_index: number;
    description: (string | null);
    module_tag: (string | null);
    color: (string | null);
};

export type TaskProfileItemUpdate = {
    name?: (string | null);
    duration_days?: (number | null);
    order_index?: (number | null);
    description?: (string | null);
    module_tag?: (string | null);
    color?: (string | null);
};

export type TaskProfilePublic = {
    id: string;
    name: string;
    description: (string | null);
    created_by: string;
    created_by_name?: (string | null);
    company_id?: (string | null);
    created_at: string;
    items?: Array<TaskProfileItemPublic>;
};

export type TaskProfileUpdate = {
    name?: (string | null);
    description?: (string | null);
};

/**
 * Response after saving a progress-report image to storage.
 */
export type TaskProgressPhotoUploadPublic = {
    photo_url: string;
};

export type TaskProgressReportPublic = {
    id: string;
    task_id: string;
    reporter_id: string;
    reporter_name?: (string | null);
    photo_url: string;
    progress_percent: number;
    note: (string | null);
    gps_lat?: (number | null);
    gps_lng?: (number | null);
    gps_accuracy_m?: (number | null);
    checkin_skipped?: boolean;
    distance_m?: (number | null);
    location_valid?: (boolean | null);
    review_status?: string;
    reviewer_id?: (string | null);
    reviewed_at?: (string | null);
    review_note?: (string | null);
    created_at: string;
};

export type TaskPublic = {
    name: string;
    description?: (string | null);
    priority?: string;
    start_time: string;
    end_time: string;
    id: string;
    project_id: string;
    parent_id: (string | null);
    level: number;
    status: string;
    computed_status?: (string | null);
    assignor_id: string;
    assignee_id: string;
    assignee_name?: (string | null);
    assignor_name?: (string | null);
    assignee_department_id?: (string | null);
    assignee_department_name?: (string | null);
    actual_end_time: (string | null);
    is_on_critical_path: boolean;
    created_at: string;
    updated_at: string;
    reported_progress_total?: number;
    progress_weight?: (number | null);
    requires_checkin?: boolean;
    checkin_lat?: (number | null);
    checkin_lng?: (number | null);
    checkin_radius_m?: number;
    module_tag?: (string | null);
    linked_entity_type?: (string | null);
    linked_entity_id?: (string | null);
    linked_entities?: Array<TaskLinkedEntityPublic>;
    blocked_by?: Array<BlockerInfo>;
    extra_assignees?: Array<TaskAssigneePublic>;
    observers?: Array<TaskObserverPublic>;
    color?: (string | null);
    performance_coefficient?: (number | null);
};

export type TaskReassignRequest = {
    new_assignee_id: string;
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskStatusUpdate = {
    status: string;
    note?: (string | null);
};

export type TaskUpdate = {
    name?: (string | null);
    description?: (string | null);
    priority?: (string | null);
    start_time?: (string | null);
    end_time?: (string | null);
    assignee_id?: (string | null);
    module_tag?: (string | null);
    linked_entity_type?: (string | null);
    linked_entity_id?: (string | null);
    color?: (string | null);
    performance_coefficient?: (number | null);
    progress_weight?: (number | null);
    requires_checkin?: (boolean | null);
    checkin_lat?: (number | null);
    checkin_lng?: (number | null);
    checkin_radius_m?: (number | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
    refresh_token?: (string | null);
    session_id?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCompanyRoleCreate = {
    user_id: string;
    company_id: string;
    role_id: string;
    is_primary?: boolean;
};

export type UserCompanyRolePublic = {
    id: string;
    user_id: string;
    company_id: string;
    role_id: string;
    role_name: string;
    role_display_name: string;
    company_name: string;
    is_primary: boolean;
    assigned_at: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserDepartmentAssign = {
    user_id: string;
    department_id?: (string | null);
};

export type UserPermissionsResponse = {
    user_id: string;
    is_superuser: boolean;
    source: string;
    total: number;
    by_module: {
        [key: string]: Array<PermissionItem>;
    };
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    company_id?: (string | null);
    department_id?: (string | null);
    job_title?: (string | null);
    availability_status?: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VapidKeyResponse = {
    public_key: (string | null);
};

export type AdminStatsGetOverviewResponse = ({
    [key: string]: unknown;
});

export type AdminStatsListActiveSessionsResponse = (Array<{
    [key: string]: unknown;
}>);

export type AdminStatsGetLoginFrequencyData = {
    days?: number;
};

export type AdminStatsGetLoginFrequencyResponse = (Array<{
    [key: string]: unknown;
}>);

export type AdminStatsGetUsersActivityData = {
    days?: number;
    limit?: number;
};

export type AdminStatsGetUsersActivityResponse = (Array<{
    [key: string]: unknown;
}>);

export type AdminStatsListAuditLogData = {
    action?: (string | null);
    actorId?: (string | null);
    entityType?: (string | null);
    limit?: number;
};

export type AdminStatsListAuditLogResponse = (Array<{
    [key: string]: unknown;
}>);

export type AdminStatsRevokeSessionData = {
    sessionId: string;
};

export type AdminStatsRevokeSessionResponse = (void);

export type AdminUsersListUsersResponse = (Array<AdminUserListRow>);

export type AdminUsersGetUserDetailData = {
    userId: string;
};

export type AdminUsersGetUserDetailResponse = (AdminUserDetail);

export type AdminUsersAddMembershipData = {
    requestBody: MembershipCreate;
    userId: string;
};

export type AdminUsersAddMembershipResponse = (AdminUserMembership);

export type AdminUsersUpdateMembershipData = {
    companyId: string;
    requestBody: MembershipUpdate;
    userId: string;
};

export type AdminUsersUpdateMembershipResponse = (Array<AdminUserMembership>);

export type AdminUsersDeleteMembershipData = {
    companyId: string;
    userId: string;
};

export type AdminUsersDeleteMembershipResponse = (void);

export type AdminUsersGetUserPermissionsData = {
    userId: string;
};

export type AdminUsersGetUserPermissionsResponse = (UserPermissionsResponse);

export type AttendanceCheckInData = {
    formData: Body_attendance_check_in;
};

export type AttendanceCheckInResponse = (AttendanceRecordPublic);

export type AttendanceCheckOutData = {
    formData: Body_attendance_check_out;
};

export type AttendanceCheckOutResponse = (AttendanceRecordPublic);

export type AttendanceAdjustAttendanceHoursData = {
    recordId: string;
    requestBody: _AdjustHoursRequest;
};

export type AttendanceAdjustAttendanceHoursResponse = (AttendanceRecordPublic);

export type AttendanceMyAttendanceData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
};

export type AttendanceMyAttendanceResponse = (AttendanceRecordsPublic);

export type AttendanceProjectAttendanceData = {
    projectId: string;
    workDate?: (string | null);
};

export type AttendanceProjectAttendanceResponse = (AttendanceRecordsPublic);

export type AttendanceAttendanceTaskSuggestionsResponse = (Array<(string)>);

export type AttendanceSetCompanySiteLocationData = {
    companyId: string;
    requestBody: SiteLocationUpdate;
};

export type AttendanceSetCompanySiteLocationResponse = (CompanyPublic);

export type AttendanceSetSiteLocationData = {
    projectId: string;
    requestBody: SiteLocationUpdate;
};

export type AttendanceSetSiteLocationResponse = (ProjectPublic);

export type ChatListMyRoomsResponse = (Array<ChatRoomPublic>);

export type ChatCreateRoomData = {
    requestBody: ChatRoomCreate;
};

export type ChatCreateRoomResponse = (ChatRoomPublic);

export type ChatGetRoomData = {
    roomId: string;
};

export type ChatGetRoomResponse = (ChatRoomPublic);

export type ChatUpdateRoomData = {
    requestBody: ChatRoomUpdate;
    roomId: string;
};

export type ChatUpdateRoomResponse = (ChatRoomPublic);

export type ChatDeleteRoomData = {
    roomId: string;
};

export type ChatDeleteRoomResponse = (void);

export type ChatGetUnreadCountResponse = (ChatUnreadCountPublic);

export type ChatMarkRoomReadData = {
    roomId: string;
};

export type ChatMarkRoomReadResponse = (void);

export type ChatListMembersData = {
    roomId: string;
};

export type ChatListMembersResponse = (Array<ChatMemberWithUserPublic>);

export type ChatAddMemberData = {
    requestBody: ChatMemberAdd;
    roomId: string;
};

export type ChatAddMemberResponse = (ChatMemberWithUserPublic);

export type ChatRemoveMemberData = {
    roomId: string;
    userId: string;
};

export type ChatRemoveMemberResponse = (void);

export type ChatListMessagesData = {
    beforeId?: (string | null);
    limit?: number;
    roomId: string;
};

export type ChatListMessagesResponse = (Array<ChatMessagePublic>);

export type ChatCreateMessageData = {
    requestBody: ChatMessageCreate;
    roomId: string;
};

export type ChatCreateMessageResponse = (ChatMessagePublic);

export type ChatUploadAttachmentData = {
    formData: Body_chat_upload_attachment;
    roomId: string;
};

export type ChatUploadAttachmentResponse = (ChatAttachmentPublic);

export type ContractsListContractsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type ContractsListContractsResponse = (ContractsPublic);

export type ContractsCreateContractData = {
    requestBody: ContractCreate;
};

export type ContractsCreateContractResponse = (ContractPublic);

export type ContractsGetContractData = {
    contractId: string;
};

export type ContractsGetContractResponse = (ContractWithDetailsPublic);

export type ContractsUpdateContractData = {
    contractId: string;
    requestBody: ContractUpdate;
};

export type ContractsUpdateContractResponse = (ContractPublic);

export type ContractsDeleteContractData = {
    contractId: string;
};

export type ContractsDeleteContractResponse = (void);

export type ContractsSubmitContractData = {
    contractId: string;
    requestBody: ContractActionRequest;
};

export type ContractsSubmitContractResponse = (ContractPublic);

export type ContractsApproveContractData = {
    contractId: string;
    requestBody: ContractActionRequest;
};

export type ContractsApproveContractResponse = (ContractPublic);

export type ContractsRejectContractData = {
    contractId: string;
    requestBody: ContractActionRequest;
};

export type ContractsRejectContractResponse = (ContractPublic);

export type ContractsSignContractData = {
    contractId: string;
    requestBody: ContractSignRequest;
};

export type ContractsSignContractResponse = (ContractPublic);

export type ContractsConfirmAdvanceData = {
    contractId: string;
    requestBody: ContractConfirmAdvanceRequest;
};

export type ContractsConfirmAdvanceResponse = (ContractPublic);

export type ContractsStartProductionData = {
    contractId: string;
    requestBody: ContractActionRequest;
};

export type ContractsStartProductionResponse = (ContractPublic);

export type ContractsCompleteContractData = {
    contractId: string;
    requestBody: ContractActionRequest;
};

export type ContractsCompleteContractResponse = (ContractPublic);

export type ContractsUploadAttachmentData = {
    contractId: string;
    description?: (string | null);
    fileType?: string;
    formData: Body_contracts_upload_attachment;
    phase?: (string | null);
};

export type ContractsUploadAttachmentResponse = (ContractAttachmentPublic);

export type ContractsDeleteAttachmentData = {
    attId: string;
    contractId: string;
};

export type ContractsDeleteAttachmentResponse = (void);

export type CustomerCompaniesCreateCustomerCompanyData = {
    requestBody: CustomerCompanyCreate;
};

export type CustomerCompaniesCreateCustomerCompanyResponse = (CustomerCompanyPublic);

export type CustomerCompaniesListCustomerCompaniesData = {
    includeInactive?: boolean;
    q?: (string | null);
    type?: (string | null);
};

export type CustomerCompaniesListCustomerCompaniesResponse = (CustomerCompaniesPublic);

export type CustomerCompaniesGetCustomerCompanyData = {
    customerId: string;
};

export type CustomerCompaniesGetCustomerCompanyResponse = (CustomerCompanyPublic);

export type CustomerCompaniesUpdateCustomerCompanyData = {
    customerId: string;
    requestBody: CustomerCompanyUpdate;
};

export type CustomerCompaniesUpdateCustomerCompanyResponse = (CustomerCompanyPublic);

export type CustomerCompaniesDeleteCustomerCompanyData = {
    customerId: string;
};

export type CustomerCompaniesDeleteCustomerCompanyResponse = (void);

export type DashboardOverviewData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardOverviewResponse = ({
    [key: string]: unknown;
});

export type DashboardProjectStatsData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardProjectStatsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardUserWorkloadData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardUserWorkloadResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardLeaderboardData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardLeaderboardResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardOverdueReportData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardOverdueReportResponse = ({
    [key: string]: unknown;
});

export type DashboardUserTasksData = {
    userId: string;
};

export type DashboardUserTasksResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardCompanyGanttData = {
    assigneeId?: (string | null);
    departmentId?: (string | null);
    endDate?: (string | null);
    projectId?: (string | null);
    startDate?: (string | null);
};

export type DashboardCompanyGanttResponse = ({
    [key: string]: unknown;
});

export type DashboardUserGanttData = {
    userId: string;
};

export type DashboardUserGanttResponse = ({
    [key: string]: unknown;
});

export type DashboardUserWeeklyStatsData = {
    userId: string;
};

export type DashboardUserWeeklyStatsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardTaskCalendarData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardTaskCalendarResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardTeamProductivityData = {
    departmentId?: (string | null);
    /**
     * YYYY-MM, default: current
     */
    month?: (string | null);
    projectId?: (string | null);
};

export type DashboardTeamProductivityResponse = ({
    [key: string]: unknown;
});

export type DashboardYearSummaryData = {
    departmentId?: (string | null);
    /**
     * YYYY-MM (ghi đè ngày bắt đầu)
     */
    fromMonth?: (string | null);
    projectId?: (string | null);
    /**
     * YYYY-MM (ghi đè ngày kết thúc)
     */
    toMonth?: (string | null);
    /**
     * Năm, mặc định năm hiện tại
     */
    year?: (number | null);
};

export type DashboardYearSummaryResponse = ({
    [key: string]: unknown;
});

export type ExportExportFullResponse = (unknown);

export type ExportExportAccountsResponse = (unknown);

export type ExportExportTasksResponse = (unknown);

export type IncidentsCreateIncidentData = {
    requestBody: IncidentCreate;
};

export type IncidentsCreateIncidentResponse = (IncidentPublic);

export type IncidentsListIncidentsData = {
    category?: (string | null);
    limit?: number;
    projectId?: (string | null);
    /**
     * Tìm theo tiêu đề/mô tả/giải pháp
     */
    q?: (string | null);
    skip?: number;
    status?: (string | null);
};

export type IncidentsListIncidentsResponse = (IncidentsPublic);

export type IncidentsGetIncidentData = {
    incidentId: string;
};

export type IncidentsGetIncidentResponse = (IncidentPublic);

export type IncidentsUpdateIncidentData = {
    incidentId: string;
    requestBody: IncidentUpdate;
};

export type IncidentsUpdateIncidentResponse = (IncidentPublic);

export type IncidentsResolveIncidentData = {
    incidentId: string;
    requestBody: IncidentResolve;
};

export type IncidentsResolveIncidentResponse = (IncidentPublic);

export type IncidentsAddIncidentAttachmentData = {
    formData: Body_incidents_add_incident_attachment;
    incidentId: string;
};

export type IncidentsAddIncidentAttachmentResponse = (IncidentAttachmentPublic);

export type LeaveCreateLeaveRequestData = {
    requestBody: LeaveRequestCreate;
};

export type LeaveCreateLeaveRequestResponse = (LeaveRequestPublic);

export type LeaveMyLeaveRequestsData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    status?: (string | null);
};

export type LeaveMyLeaveRequestsResponse = (LeaveRequestsPublic);

export type LeaveCancelLeaveRequestData = {
    requestId: string;
};

export type LeaveCancelLeaveRequestResponse = (LeaveRequestPublic);

export type LeavePendingLeaveRequestsResponse = (LeaveRequestsPublic);

export type LeaveApproveLeaveRequestData = {
    requestBody: LeaveDecisionRequest;
    requestId: string;
};

export type LeaveApproveLeaveRequestResponse = (LeaveRequestPublic);

export type LeaveRejectLeaveRequestData = {
    requestBody: LeaveDecisionRequest;
    requestId: string;
};

export type LeaveRejectLeaveRequestResponse = (LeaveRequestPublic);

export type LeaveCompanyLeaveRequestsData = {
    companyId: string;
    dateFrom?: (string | null);
    dateTo?: (string | null);
    status?: (string | null);
};

export type LeaveCompanyLeaveRequestsResponse = (LeaveRequestsPublic);

export type LeaveGetLeaveApproverConfigData = {
    companyId: string;
};

export type LeaveGetLeaveApproverConfigResponse = (LeaveApproverConfigListPublic);

export type LeaveSetLeaveApproverConfigData = {
    companyId: string;
    requestBody: LeaveApproverConfigUpdate;
};

export type LeaveSetLeaveApproverConfigResponse = (LeaveApproverConfigListPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRefreshAccessTokenData = {
    requestBody: RefreshTokenRequest;
};

export type LoginRefreshAccessTokenResponse = (Token);

export type LoginLogoutData = {
    requestBody: LogoutRequest;
};

export type LoginLogoutResponse = (Message);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NotificationsListNotificationsData = {
    limit?: number;
    skip?: number;
};

export type NotificationsListNotificationsResponse = (Array<NotificationPublic>);

export type NotificationsUnreadCountResponse = (NotificationUnreadCount);

export type NotificationsMarkReadData = {
    notificationId: string;
};

export type NotificationsMarkReadResponse = (NotificationPublic);

export type NotificationsMarkAllReadResponse = (void);

export type NotificationsGetVapidPublicKeyResponse = (VapidKeyResponse);

export type NotificationsSubscribePushData = {
    requestBody: PushSubscribeRequest;
};

export type NotificationsSubscribePushResponse = (void);

export type NotificationsUnsubscribePushData = {
    requestBody: PushSubscribeRequest;
};

export type NotificationsUnsubscribePushResponse = (void);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsListProjectsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type ProjectsListProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsGetProjectData = {
    projectId: string;
};

export type ProjectsGetProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    projectId: string;
};

export type ProjectsDeleteProjectResponse = (void);

export type ProjectsUpsertLevelConfigData = {
    projectId: string;
    requestBody: TaskLevelConfigCreate;
};

export type ProjectsUpsertLevelConfigResponse = (TaskLevelConfigPublic);

export type ProjectsGetLevelConfigsData = {
    projectId: string;
};

export type ProjectsGetLevelConfigsResponse = (Array<TaskLevelConfigPublic>);

export type ProjectsGetMembersData = {
    projectId: string;
};

export type ProjectsGetMembersResponse = (Array<ProjectMemberWithUserPublic>);

export type ProjectsAddMemberData = {
    projectId: string;
    roleId: string;
    userId: string;
};

export type ProjectsAddMemberResponse = ({
    [key: string]: unknown;
});

export type ProjectsRemoveMemberData = {
    projectId: string;
    userId: string;
};

export type ProjectsRemoveMemberResponse = (void);

export type ProjectsGetDelayWarningsData = {
    projectId: string;
};

export type ProjectsGetDelayWarningsResponse = (DelayWarningsPublic);

export type ProjectsCreateProjectChatRoomData = {
    projectId: string;
};

export type ProjectsCreateProjectChatRoomResponse = (ChatRoomPublic);

export type QuotationsCreateQuotationData = {
    requestBody: QuotationCreate;
};

export type QuotationsCreateQuotationResponse = (QuotationPublic);

export type QuotationsListQuotationsData = {
    clientCompanyName?: (string | null);
    currentStage?: (string | null);
    dateFrom?: (string | null);
    dateTo?: (string | null);
    equipmentCategory?: (string | null);
    limit?: number;
    outcome?: (string | null);
    salesOwnerId?: (string | null);
    skip?: number;
    status?: (string | null);
};

export type QuotationsListQuotationsResponse = (QuotationsPublic);

export type QuotationsListCompaniesResponse = (Array<(string)>);

export type QuotationsListCompanyProfilesResponse = (Array<QuotationCompanyProfilePublic>);

export type QuotationsMyPendingQuotationsResponse = (Array<QuotationPublic>);

export type QuotationsGetQuotationData = {
    quotationId: string;
};

export type QuotationsGetQuotationResponse = (QuotationPublic);

export type QuotationsUpdateQuotationData = {
    quotationId: string;
    requestBody: QuotationUpdate;
};

export type QuotationsUpdateQuotationResponse = (QuotationPublic);

export type QuotationsDeleteQuotationData = {
    quotationId: string;
};

export type QuotationsDeleteQuotationResponse = (void);

export type QuotationsSubmitSurveyData = {
    quotationId: string;
    requestBody: QuotationSubmitSurveyRequest;
};

export type QuotationsSubmitSurveyResponse = (QuotationPublic);

export type QuotationsApproveSurveyData = {
    quotationId: string;
    requestBody: QuotationApproveRequest;
};

export type QuotationsApproveSurveyResponse = (QuotationPublic);

export type QuotationsSubmitDesignData = {
    quotationId: string;
    requestBody: QuotationSubmitDesignRequest;
};

export type QuotationsSubmitDesignResponse = (QuotationPublic);

export type QuotationsSubmitBocTachData = {
    quotationId: string;
    requestBody: QuotationSubmitBocTachRequest;
};

export type QuotationsSubmitBocTachResponse = (QuotationPublic);

export type QuotationsApproveDesignData = {
    quotationId: string;
    requestBody: QuotationApproveRequest;
};

export type QuotationsApproveDesignResponse = (QuotationPublic);

export type QuotationsSubmitPricingData = {
    quotationId: string;
    requestBody: QuotationSubmitPricingRequest;
};

export type QuotationsSubmitPricingResponse = (QuotationPublic);

export type QuotationsFinalizeData = {
    quotationId: string;
    requestBody: QuotationFinalizeRequest;
};

export type QuotationsFinalizeResponse = (QuotationPublic);

export type QuotationsApproveFinalData = {
    quotationId: string;
    requestBody: QuotationApproveRequest;
};

export type QuotationsApproveFinalResponse = (QuotationPublic);

export type QuotationsSendToClientData = {
    quotationId: string;
    requestBody: QuotationSendToClientRequest;
};

export type QuotationsSendToClientResponse = (QuotationPublic);

export type QuotationsSubmitNegotiationData = {
    quotationId: string;
    requestBody: QuotationSubmitNegotiationRequest;
};

export type QuotationsSubmitNegotiationResponse = (QuotationPublic);

export type QuotationsApproveNegotiationData = {
    quotationId: string;
    requestBody: QuotationApproveRequest;
};

export type QuotationsApproveNegotiationResponse = (QuotationPublic);

export type QuotationsCloseQuotationData = {
    quotationId: string;
    requestBody: QuotationCloseRequest;
};

export type QuotationsCloseQuotationResponse = (QuotationPublic);

export type QuotationsListApprovalParticipantsData = {
    quotationId: string;
};

export type QuotationsListApprovalParticipantsResponse = (Array<QuotationApprovalParticipantPublic>);

export type QuotationsAddApprovalParticipantData = {
    quotationId: string;
    requestBody: QuotationApprovalParticipantCreate;
};

export type QuotationsAddApprovalParticipantResponse = (QuotationApprovalParticipantPublic);

export type QuotationsRemoveApprovalParticipantData = {
    participantId: string;
    quotationId: string;
};

export type QuotationsRemoveApprovalParticipantResponse = (void);

export type QuotationsParticipantApproveData = {
    quotationId: string;
    requestBody: _ParticipantApproveRequest;
};

export type QuotationsParticipantApproveResponse = (QuotationPublic);

export type QuotationsListHistoryData = {
    quotationId: string;
};

export type QuotationsListHistoryResponse = (Array<QuotationStageTransitionPublic>);

export type QuotationsListNegotiationsData = {
    quotationId: string;
};

export type QuotationsListNegotiationsResponse = (Array<QuotationNegotiationLogPublic>);

export type QuotationsAddNegotiationLogData = {
    quotationId: string;
    requestBody: QuotationNegotiationLogCreate;
};

export type QuotationsAddNegotiationLogResponse = (QuotationNegotiationLogPublic);

export type QuotationsListAttachmentsData = {
    quotationId: string;
};

export type QuotationsListAttachmentsResponse = (Array<QuotationAttachmentPublic>);

export type QuotationsAddAttachmentData = {
    quotationId: string;
    requestBody: QuotationAttachmentCreate;
};

export type QuotationsAddAttachmentResponse = (QuotationAttachmentPublic);

export type QuotationsUploadAttachmentFileData = {
    description?: (string | null);
    formData: Body_quotations_upload_attachment_file;
    quotationId: string;
};

export type QuotationsUploadAttachmentFileResponse = (QuotationAttachmentPublic);

export type QuotationsDeleteAttachmentData = {
    attId: string;
    quotationId: string;
};

export type QuotationsDeleteAttachmentResponse = (void);

export type QuotationsListVersionsData = {
    quotationId: string;
};

export type QuotationsListVersionsResponse = (Array<QuotationVersionPublic>);

export type QuotationsCreateVersionSnapshotData = {
    quotationId: string;
    reason?: string;
};

export type QuotationsCreateVersionSnapshotResponse = (QuotationVersionPublic);

export type QuotationsGetVersionData = {
    quotationId: string;
    versionId: string;
};

export type QuotationsGetVersionResponse = (QuotationVersionPublic);

export type QuotationsReportSummaryData = {
    clientCompanyName?: (string | null);
    dateFrom?: (string | null);
    dateTo?: (string | null);
    equipmentCategory?: (string | null);
};

export type QuotationsReportSummaryResponse = (QuotationReportSummary);

export type QuotationsReportByClientData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
};

export type QuotationsReportByClientResponse = (Array<QuotationByClientRow>);

export type QuotationsReportByEquipmentData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
};

export type QuotationsReportByEquipmentResponse = (Array<QuotationByEquipmentRow>);

export type QuotationsReportLostAnalysisData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
};

export type QuotationsReportLostAnalysisResponse = (Array<QuotationLostReasonRow>);

export type RolesListRoleDependenciesData = {
    companyId: string;
    relationType?: (string | null);
};

export type RolesListRoleDependenciesResponse = (Array<RoleDependencyPublic>);

export type RolesListCompanyRolesData = {
    companyId: string;
};

export type RolesListCompanyRolesResponse = (Array<Role>);

export type RolesMyPermissionsResponse = (Array<(string)>);

export type RolesPermissionsCatalogResponse = (Array<PermissionPublic>);

export type RolesRolePermissionsData = {
    roleId: string;
};

export type RolesRolePermissionsResponse = (Array<(string)>);

export type RolesAssignRolePermissionsData = {
    requestBody: RolePermissionAssignRequest;
    roleId: string;
};

export type RolesAssignRolePermissionsResponse = (RolePermissionAssignResponse);

export type RolesListCompaniesResponse = (Array<CompanyPublic>);

export type RolesCreateCompanyData = {
    requestBody: CompanyCreate;
};

export type RolesCreateCompanyResponse = (CompanyPublic);

export type RolesListMyCompaniesResponse = (Array<CompanyPublic>);

export type RolesListCompanyMembersData = {
    companyId: string;
};

export type RolesListCompanyMembersResponse = (Array<CompanyMemberPublic>);

export type RolesUpdateCompanyData = {
    companyId: string;
    requestBody: CompanyUpdate;
};

export type RolesUpdateCompanyResponse = (CompanyPublic);

export type RolesCreateDepartmentData = {
    companyId: string;
    requestBody: DepartmentCreate;
};

export type RolesCreateDepartmentResponse = (DepartmentPublic);

export type RolesListDepartmentsData = {
    companyId: string;
};

export type RolesListDepartmentsResponse = (Array<DepartmentPublic>);

export type RolesUpdateDepartmentData = {
    companyId: string;
    departmentId: string;
    requestBody: DepartmentUpdate;
};

export type RolesUpdateDepartmentResponse = (DepartmentPublic);

export type RolesDeleteDepartmentData = {
    companyId: string;
    departmentId: string;
};

export type RolesDeleteDepartmentResponse = (void);

export type RolesAssignUserToDepartmentData = {
    companyId: string;
    departmentId: string;
    requestBody: UserDepartmentAssign;
};

export type RolesAssignUserToDepartmentResponse = (DepartmentPublic);

export type RolesUnassignUserFromDepartmentData = {
    companyId: string;
    userId: string;
};

export type RolesUnassignUserFromDepartmentResponse = (void);

export type RolesCreateRoleData = {
    companyId: string;
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (Role);

export type RolesCreateRoleDependencyData = {
    requestBody: RoleDependencyCreate;
};

export type RolesCreateRoleDependencyResponse = (RoleDependencyPublic);

export type RolesAssignUserCompanyRoleData = {
    requestBody: UserCompanyRoleCreate;
};

export type RolesAssignUserCompanyRoleResponse = (UserCompanyRolePublic);

export type RolesUpdateCompanyMemberRoleData = {
    companyId: string;
    requestBody: CompanyMemberRoleUpdateRequest;
    userId: string;
};

export type RolesUpdateCompanyMemberRoleResponse = (UserCompanyRolePublic);

export type RolesRemoveCompanyMemberRoleData = {
    companyId: string;
    roleId: string;
    userId: string;
};

export type RolesRemoveCompanyMemberRoleResponse = (void);

export type RolesListUserCompanyRolesData = {
    userId: string;
};

export type RolesListUserCompanyRolesResponse = (Array<UserCompanyRolePublic>);

export type RolesMyAccountProfileResponse = (AccountProfilePublic);

export type RolesGetOrgTreeData = {
    companyId: string;
    departmentId?: (string | null);
};

export type RolesGetOrgTreeResponse = (OrgTreePublic);

export type TaskProfilesListProfilesData = {
    companyId?: (string | null);
};

export type TaskProfilesListProfilesResponse = (Array<TaskProfilePublic>);

export type TaskProfilesCreateProfileData = {
    requestBody: TaskProfileCreate;
};

export type TaskProfilesCreateProfileResponse = (TaskProfilePublic);

export type TaskProfilesGetProfileData = {
    profileId: string;
};

export type TaskProfilesGetProfileResponse = (TaskProfilePublic);

export type TaskProfilesUpdateProfileData = {
    profileId: string;
    requestBody: TaskProfileUpdate;
};

export type TaskProfilesUpdateProfileResponse = (TaskProfilePublic);

export type TaskProfilesDeleteProfileData = {
    profileId: string;
};

export type TaskProfilesDeleteProfileResponse = (void);

export type TaskProfilesAddProfileItemData = {
    profileId: string;
    requestBody: TaskProfileItemCreate;
};

export type TaskProfilesAddProfileItemResponse = (TaskProfileItemPublic);

export type TaskProfilesUpdateProfileItemData = {
    itemId: string;
    requestBody: TaskProfileItemUpdate;
};

export type TaskProfilesUpdateProfileItemResponse = (TaskProfileItemPublic);

export type TaskProfilesDeleteProfileItemData = {
    itemId: string;
};

export type TaskProfilesDeleteProfileItemResponse = (void);

export type TaskProfilesApplyProfileData = {
    profileId: string;
    requestBody: ApplyProfileRequest;
};

export type TaskProfilesApplyProfileResponse = (Array<{
    [key: string]: unknown;
}>);

export type TaskProfilesSaveTaskAsProfileData = {
    requestBody: SaveAsProfileRequest;
    taskId: string;
};

export type TaskProfilesSaveTaskAsProfileResponse = (TaskProfilePublic);

export type TasksCreateRootTaskData = {
    projectId: string;
    requestBody: TaskCreate;
};

export type TasksCreateRootTaskResponse = (TaskPublic);

export type TasksListProjectTasksData = {
    assigneeId?: (string | null);
    limit?: number;
    parentId?: (string | null);
    projectId: string;
    skip?: number;
};

export type TasksListProjectTasksResponse = (TasksPublic);

export type TasksCreateChildTaskData = {
    parentId: string;
    requestBody: TaskCreate;
};

export type TasksCreateChildTaskResponse = (TaskPublic);

export type TasksMyDashboardResponse = ({
    [key: string]: unknown;
});

export type TasksGetTaskData = {
    taskId: string;
};

export type TasksGetTaskResponse = (TaskPublic);

export type TasksUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    taskId: string;
};

export type TasksDeleteTaskResponse = (void);

export type TasksUpdateTaskStatusData = {
    requestBody: TaskStatusUpdate;
    taskId: string;
};

export type TasksUpdateTaskStatusResponse = (TaskPublic);

export type TasksAddExtraAssigneeData = {
    requestBody: TaskAssigneeAdd;
    taskId: string;
};

export type TasksAddExtraAssigneeResponse = (TaskPublic);

export type TasksRemoveExtraAssigneeData = {
    taskId: string;
    userId: string;
};

export type TasksRemoveExtraAssigneeResponse = (TaskPublic);

export type TasksAddObserverData = {
    requestBody: TaskObserverAdd;
    taskId: string;
};

export type TasksAddObserverResponse = (TaskPublic);

export type TasksRemoveObserverData = {
    taskId: string;
    userId: string;
};

export type TasksRemoveObserverResponse = (TaskPublic);

export type TasksReassignTaskData = {
    requestBody: TaskReassignRequest;
    taskId: string;
};

export type TasksReassignTaskResponse = (TaskPublic);

export type TasksCloneTaskData = {
    newAssigneeId?: (string | null);
    taskId: string;
};

export type TasksCloneTaskResponse = (TaskPublic);

export type TasksAddCommentData = {
    requestBody: TaskCommentCreate;
    taskId: string;
};

export type TasksAddCommentResponse = (TaskCommentPublic);

export type TasksListCommentsData = {
    taskId: string;
};

export type TasksListCommentsResponse = (Array<TaskCommentPublic>);

export type TasksApproveDelayRequestData = {
    commentId: string;
    requestBody: TaskCommentApprovalUpdate;
    taskId: string;
};

export type TasksApproveDelayRequestResponse = (TaskCommentPublic);

export type TasksAddDependencyData = {
    requestBody: TaskDependencyCreate;
    taskId: string;
};

export type TasksAddDependencyResponse = ({
    [key: string]: unknown;
});

export type TasksRemoveDependencyData = {
    depId: string;
    taskId: string;
};

export type TasksRemoveDependencyResponse = (void);

export type TasksGetProjectGanttData = {
    projectId: string;
};

export type TasksGetProjectGanttResponse = (GanttPublic);

export type TasksUploadProgressReportPhotoData = {
    formData: Body_tasks_upload_progress_report_photo;
    taskId: string;
};

export type TasksUploadProgressReportPhotoResponse = (TaskProgressPhotoUploadPublic);

export type TasksAddProgressReportData = {
    formData: Body_tasks_add_progress_report;
    taskId: string;
};

export type TasksAddProgressReportResponse = (TaskProgressReportPublic);

export type TasksListProgressReportsData = {
    taskId: string;
};

export type TasksListProgressReportsResponse = (Array<TaskProgressReportPublic>);

export type TasksReviewProgressReportData = {
    reportId: string;
    reviewNote?: (string | null);
    reviewStatus: string;
    taskId: string;
};

export type TasksReviewProgressReportResponse = (TaskProgressReportPublic);

export type TasksGetTaskAuditData = {
    taskId: string;
};

export type TasksGetTaskAuditResponse = (Array<AuditLogPublic>);

export type TasksCheckConflictsData = {
    taskId: string;
};

export type TasksCheckConflictsResponse = ({
    [key: string]: unknown;
});

export type UsersReadUserByEmailData = {
    email: string;
};

export type UsersReadUserByEmailResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);