// This file is auto-generated by @hey-api/openapi-ts

export type AccountMembershipPublic = {
    company_id: string;
    company_name: string;
    role_id: string;
    role_name: string;
    role_display_name: string;
    role_level: number;
    is_primary: boolean;
};

export type AccountProfilePublic = {
    user_id: string;
    email: string;
    full_name: (string | null);
    memberships: Array<AccountMembershipPublic>;
};

export type AuditLogPublic = {
    id: string;
    actor_id: string;
    action: string;
    entity_type: string;
    entity_id: string;
    old_value: (unknown | null);
    new_value: (unknown | null);
    created_at: string;
};

export type Body_chat_upload_attachment = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_tasks_upload_progress_report_photo = {
    file: (Blob | File);
};

/**
 * Chat attachment response.
 */
export type ChatAttachmentPublic = {
    id: string;
    message_id: string;
    filename: string;
    mime_type: (string | null);
    size_bytes: (number | null);
    public_url: (string | null);
    created_at: string;
};

/**
 * Add a member to a room.
 */
export type ChatMemberAdd = {
    user_id: string;
    role?: 'owner' | 'admin' | 'member';
};

export type role = 'owner' | 'admin' | 'member';

/**
 * Chat member response enriched with basic user info.
 */
export type ChatMemberWithUserPublic = {
    room_id: string;
    user_id: string;
    role: string;
    joined_at: string;
    left_at: (string | null);
    email: string;
    full_name?: (string | null);
};

/**
 * Create a message in a room (text only).
 */
export type ChatMessageCreate = {
    content: string;
};

/**
 * Chat message response.
 */
export type ChatMessagePublic = {
    id: string;
    room_id: string;
    sender_id: string;
    message_type: string;
    content: (string | null);
    created_at: string;
};

/**
 * Create a chat room (direct/group).
 */
export type ChatRoomCreate = {
    room_type?: 'direct' | 'group';
    name?: (string | null);
    room_color?: (string | null);
    member_user_ids?: Array<(string)>;
};

export type room_type = 'direct' | 'group';

/**
 * Chat room response.
 */
export type ChatRoomPublic = {
    id: string;
    company_id: string;
    room_type: string;
    name: (string | null);
    room_color: (string | null);
    created_by: string;
    created_at: string;
};

/**
 * Update chat room fields (currently only name).
 */
export type ChatRoomUpdate = {
    name?: (string | null);
    room_color?: (string | null);
};

export type CompanyCreate = {
    name: string;
    slug: string;
};

export type CompanyPublic = {
    id: string;
    name: string;
    slug: string;
    is_active: boolean;
};

export type CompanyUpdate = {
    name?: (string | null);
    is_active?: (boolean | null);
};

export type DepartmentCreate = {
    name: string;
    parent_id?: (string | null);
    dept_type?: (string | null);
};

export type DepartmentPublic = {
    id: string;
    company_id: string;
    parent_id: (string | null);
    name: string;
    dept_type: (string | null);
    is_active: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LogoutRequest = {
    refresh_token?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrgTreeDepartmentGroupPublic = {
    department_id: (string | null);
    department_name: string;
    roles: Array<OrgTreeRoleNodePublic>;
};

export type OrgTreeMemberPublic = {
    user_id: string;
    full_name: (string | null);
    email: string;
    department_id: (string | null);
    department_name: (string | null);
    is_current_user?: boolean;
};

export type OrgTreePublic = {
    company_id: string;
    company_name: string;
    current_user_id: string;
    current_role_id: (string | null);
    current_role_level: (number | null);
    departments: Array<OrgTreeDepartmentGroupPublic>;
};

export type OrgTreeRoleNodePublic = {
    role_id: string;
    role_name: string;
    role_display_name: string;
    role_level: number;
    relation_to_current: string;
    members: Array<OrgTreeMemberPublic>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    name: string;
    code: string;
    description?: (string | null);
    start_date: string;
    end_date: string;
    status?: string;
    department_id?: (string | null);
    project_type?: (string | null);
};

/**
 * Project membership with resolved user and role labels for API clients.
 */
export type ProjectMemberWithUserPublic = {
    user_id: string;
    role_id: string;
    joined_at: string;
    full_name?: (string | null);
    email: string;
    role_display_name: string;
};

export type ProjectPublic = {
    name: string;
    code: string;
    description?: (string | null);
    start_date: string;
    end_date: string;
    status?: string;
    project_type?: string;
    id: string;
    company_id: string;
    department_id: (string | null);
    pm_id: string;
    created_at: string;
    updated_at: string;
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    name?: (string | null);
    description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    status?: (string | null);
    pm_id?: (string | null);
    project_type?: (string | null);
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

/**
 * Roles are DATA, not code.
 * System roles (is_system=True) are seeded and cannot be deleted.
 * Custom roles are created by admin via UI.
 */
export type Role = {
    id?: string;
    company_id: string;
    name: string;
    display_name: string;
    level?: number;
    is_system?: boolean;
    description?: (string | null);
    policy_doc?: ({
    [key: string]: unknown;
} | null);
    created_at?: string;
};

export type RoleCreate = {
    name: string;
    display_name: string;
    level?: number;
    description?: (string | null);
    policy_doc?: ({
    [key: string]: unknown;
} | null);
};

export type RoleDependencyCreate = {
    company_id: string;
    from_role_id: string;
    to_role_id: string;
    relation_type: 'REPORTS_TO' | 'PEERS_WITH' | 'REQUIRES_APPROVAL_FROM';
};

export type relation_type = 'REPORTS_TO' | 'PEERS_WITH' | 'REQUIRES_APPROVAL_FROM';

export type RoleDependencyPublic = {
    id: string;
    company_id: string;
    from_role_id: string;
    from_role_name: string;
    to_role_id: string;
    to_role_name: string;
    relation_type: string;
    is_active: boolean;
    created_at: string;
};

export type TaskCommentApprovalUpdate = {
    approval_status: 'APPROVED' | 'REJECTED';
};

export type approval_status = 'APPROVED' | 'REJECTED';

export type TaskCommentCreate = {
    content: string;
    comment_type?: string;
    requested_end_time?: (string | null);
    approval_status?: ('PENDING' | 'APPROVED' | 'REJECTED' | null);
};

export type TaskCommentPublic = {
    content: string;
    comment_type?: string;
    id: string;
    task_id: string;
    author_id: string;
    author_name?: (string | null);
    created_at: string;
    is_edited: boolean;
    requested_end_time: (string | null);
    approval_status: (string | null);
};

export type TaskCreate = {
    name: string;
    description?: (string | null);
    priority?: string;
    start_time: string;
    end_time: string;
    project_id: string;
    parent_id?: (string | null);
    assignee_id: string;
    extra_assignee_ids?: Array<string>;
    progress_weight?: (number | null);
};

export type TaskDependencyCreate = {
    blocking_task_id: string;
    dependent_task_id: string;
    dependency_type?: 'FS' | 'SS' | 'FF' | 'SF';
    lag_hours?: number;
};

export type dependency_type = 'FS' | 'SS' | 'FF' | 'SF';

export type TaskLevelConfigCreate = {
    level: number;
    label: string;
    requires_proof?: boolean;
    can_have_children?: boolean;
    max_children?: (number | null);
    assignable_role_ids?: (Array<(string)> | null);
};

export type TaskLevelConfigPublic = {
    id: string;
    project_id: string;
    level: number;
    label: string;
    requires_proof: boolean;
    can_have_children: boolean;
    max_children: (number | null);
};

/**
 * Response after saving a progress-report image to storage.
 */
export type TaskProgressPhotoUploadPublic = {
    photo_url: string;
};

export type TaskProgressReportCreate = {
    photo_url: string;
    progress_percent: number;
    note?: (string | null);
};

export type TaskProgressReportPublic = {
    id: string;
    task_id: string;
    reporter_id: string;
    reporter_name?: (string | null);
    photo_url: string;
    progress_percent: number;
    note: (string | null);
    gps_lat?: (number | null);
    gps_lng?: (number | null);
    gps_accuracy_m?: (number | null);
    checkin_skipped?: boolean;
    distance_m?: (number | null);
    location_valid?: (boolean | null);
    created_at: string;
};

export type TaskProofCreate = {
    file_url: string;
    file_type?: string;
    note?: (string | null);
    gps_lat?: (number | null);
    gps_lng?: (number | null);
    captured_at?: (string | null);
    device_info?: (string | null);
};

export type TaskProofPublic = {
    id: string;
    task_id: string;
    uploader_id: string;
    file_url: string;
    file_type: string;
    note: (string | null);
    gps_lat: (number | null);
    gps_lng: (number | null);
    review_status: string;
    reviewer_id: (string | null);
    uploaded_at: string;
};

export type BlockerInfo = {
    id: string;
    name: string;
    status: string;
};

export type TaskPublic = {
    name: string;
    description?: (string | null);
    priority?: string;
    start_time: string;
    end_time: string;
    id: string;
    project_id: string;
    parent_id: (string | null);
    level: number;
    status: string;
    computed_status?: (string | null);
    assignor_id: string;
    assignee_id: string;
    assignee_name?: (string | null);
    assignor_name?: (string | null);
    actual_end_time: (string | null);
    is_on_critical_path: boolean;
    created_at: string;
    updated_at: string;
    reported_progress_total?: number;
    progress_weight?: (number | null);
    module_tag?: (string | null);
    linked_entity_type?: (string | null);
    linked_entity_id?: (string | null);
    color?: (string | null);
    performance_coefficient?: (number | null);
    blocked_by?: Array<BlockerInfo>;
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskStatusUpdate = {
    status: string;
    note?: (string | null);
};

export type TaskUpdate = {
    name?: (string | null);
    description?: (string | null);
    priority?: (string | null);
    start_time?: (string | null);
    end_time?: (string | null);
    assignee_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
    refresh_token?: (string | null);
    session_id?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCompanyRoleCreate = {
    user_id: string;
    company_id: string;
    role_id: string;
    is_primary?: boolean;
};

export type UserCompanyRolePublic = {
    id: string;
    user_id: string;
    company_id: string;
    role_id: string;
    role_name: string;
    role_display_name: string;
    company_name: string;
    is_primary: boolean;
    assigned_at: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    department_id?: (string | null);
    job_title?: (string | null);
    availability_status?: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ChatListMyRoomsResponse = (Array<ChatRoomPublic>);

export type ChatCreateRoomData = {
    requestBody: ChatRoomCreate;
};

export type ChatCreateRoomResponse = (ChatRoomPublic);

export type ChatGetRoomData = {
    roomId: string;
};

export type ChatGetRoomResponse = (ChatRoomPublic);

export type ChatUpdateRoomData = {
    requestBody: ChatRoomUpdate;
    roomId: string;
};

export type ChatUpdateRoomResponse = (ChatRoomPublic);

export type ChatDeleteRoomData = {
    roomId: string;
};

export type ChatDeleteRoomResponse = (void);

export type ChatListMembersData = {
    roomId: string;
};

export type ChatListMembersResponse = (Array<ChatMemberWithUserPublic>);

export type ChatAddMemberData = {
    requestBody: ChatMemberAdd;
    roomId: string;
};

export type ChatAddMemberResponse = (ChatMemberWithUserPublic);

export type ChatRemoveMemberData = {
    roomId: string;
    userId: string;
};

export type ChatRemoveMemberResponse = (void);

export type ChatListMessagesData = {
    limit?: number;
    roomId: string;
    skip?: number;
};

export type ChatListMessagesResponse = (Array<ChatMessagePublic>);

export type ChatCreateMessageData = {
    requestBody: ChatMessageCreate;
    roomId: string;
};

export type ChatCreateMessageResponse = (ChatMessagePublic);

export type ChatUploadAttachmentData = {
    formData: Body_chat_upload_attachment;
    roomId: string;
};

export type ChatUploadAttachmentResponse = (ChatAttachmentPublic);

export type DashboardOverviewData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardOverviewResponse = ({
    [key: string]: unknown;
});

export type DashboardProjectStatsData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardProjectStatsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardUserWorkloadData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardUserWorkloadResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardLeaderboardData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardLeaderboardResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardOverdueReportData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardOverdueReportResponse = ({
    [key: string]: unknown;
});

export type DashboardTaskCalendarData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardTaskCalendarResponse = (Array<{
    [key: string]: unknown;
}>);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRefreshAccessTokenData = {
    requestBody: RefreshTokenRequest;
};

export type LoginRefreshAccessTokenResponse = (Token);

export type LoginLogoutData = {
    requestBody: LogoutRequest;
};

export type LoginLogoutResponse = (Message);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsListProjectsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type ProjectsListProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsGetProjectData = {
    projectId: string;
};

export type ProjectsGetProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsUpsertLevelConfigData = {
    projectId: string;
    requestBody: TaskLevelConfigCreate;
};

export type ProjectsUpsertLevelConfigResponse = (TaskLevelConfigPublic);

export type ProjectsGetLevelConfigsData = {
    projectId: string;
};

export type ProjectsGetLevelConfigsResponse = (Array<TaskLevelConfigPublic>);

export type ProjectsGetMembersData = {
    projectId: string;
};

export type ProjectsGetMembersResponse = (Array<ProjectMemberWithUserPublic>);

export type ProjectsAddMemberData = {
    projectId: string;
    roleId: string;
    userId: string;
};

export type ProjectsAddMemberResponse = (unknown);

export type RolesListRoleDependenciesData = {
    companyId: string;
    relationType?: (string | null);
};

export type RolesListRoleDependenciesResponse = (Array<RoleDependencyPublic>);

export type RolesListCompanyRolesData = {
    companyId: string;
};

export type RolesListCompanyRolesResponse = (Array<Role>);

export type RolesListCompaniesResponse = (Array<CompanyPublic>);

export type RolesCreateCompanyData = {
    requestBody: CompanyCreate;
};

export type RolesCreateCompanyResponse = (CompanyPublic);

export type RolesUpdateCompanyData = {
    companyId: string;
    requestBody: CompanyUpdate;
};

export type RolesUpdateCompanyResponse = (CompanyPublic);

export type RolesCreateDepartmentData = {
    companyId: string;
    requestBody: DepartmentCreate;
};

export type RolesCreateDepartmentResponse = (DepartmentPublic);

export type RolesListDepartmentsData = {
    companyId: string;
};

export type RolesListDepartmentsResponse = (Array<DepartmentPublic>);

export type RolesCreateRoleData = {
    companyId: string;
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (Role);

export type RolesCreateRoleDependencyData = {
    requestBody: RoleDependencyCreate;
};

export type RolesCreateRoleDependencyResponse = (RoleDependencyPublic);

export type RolesAssignUserCompanyRoleData = {
    requestBody: UserCompanyRoleCreate;
};

export type RolesAssignUserCompanyRoleResponse = (UserCompanyRolePublic);

export type RolesListUserCompanyRolesData = {
    userId: string;
};

export type RolesListUserCompanyRolesResponse = (Array<UserCompanyRolePublic>);

export type RolesMyAccountProfileResponse = (AccountProfilePublic);

export type RolesGetOrgTreeData = {
    companyId: string;
    departmentId?: (string | null);
};

export type RolesGetOrgTreeResponse = (OrgTreePublic);

export type TasksCreateRootTaskData = {
    projectId: string;
    requestBody: TaskCreate;
};

export type TasksCreateRootTaskResponse = (TaskPublic);

export type TasksListProjectTasksData = {
    assigneeId?: (string | null);
    limit?: number;
    parentId?: (string | null);
    projectId: string;
    skip?: number;
};

export type TasksListProjectTasksResponse = (TasksPublic);

export type TasksCreateChildTaskData = {
    parentId: string;
    requestBody: TaskCreate;
};

export type TasksCreateChildTaskResponse = (TaskPublic);

export type TasksGetTaskData = {
    taskId: string;
};

export type TasksGetTaskResponse = (TaskPublic);

export type TasksUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    taskId: string;
};

export type TasksDeleteTaskResponse = (void);

export type TasksMyDashboardResponse = ({
    [key: string]: unknown;
});

export type TasksUpdateTaskStatusData = {
    requestBody: TaskStatusUpdate;
    taskId: string;
};

export type TasksUpdateTaskStatusResponse = (TaskPublic);

export type TasksCloneTaskData = {
    newAssigneeId?: (string | null);
    taskId: string;
};

export type TasksCloneTaskResponse = (TaskPublic);

export type TasksAddCommentData = {
    requestBody: TaskCommentCreate;
    taskId: string;
};

export type TasksAddCommentResponse = (TaskCommentPublic);

export type TasksListCommentsData = {
    taskId: string;
};

export type TasksListCommentsResponse = (Array<TaskCommentPublic>);

export type TasksApproveDelayRequestData = {
    commentId: string;
    requestBody: TaskCommentApprovalUpdate;
    taskId: string;
};

export type TasksApproveDelayRequestResponse = (TaskCommentPublic);

export type TasksUploadProofData = {
    requestBody: TaskProofCreate;
    taskId: string;
};

export type TasksUploadProofResponse = (TaskProofPublic);

export type TasksListProofsData = {
    taskId: string;
};

export type TasksListProofsResponse = (Array<TaskProofPublic>);

export type TasksReviewProofData = {
    proofId: string;
    reviewNote?: (string | null);
    reviewStatus: string;
    taskId: string;
};

export type TasksReviewProofResponse = (TaskProofPublic);

export type TasksAddDependencyData = {
    requestBody: TaskDependencyCreate;
    taskId: string;
};

export type TasksAddDependencyResponse = (unknown);

export type TasksUploadProgressReportPhotoData = {
    formData: Body_tasks_upload_progress_report_photo;
    taskId: string;
};

export type TasksUploadProgressReportPhotoResponse = (TaskProgressPhotoUploadPublic);

export type TasksAddProgressReportData = {
    requestBody: TaskProgressReportCreate;
    taskId: string;
};

export type TasksAddProgressReportResponse = (TaskProgressReportPublic);

export type TasksListProgressReportsData = {
    taskId: string;
};

export type TasksListProgressReportsResponse = (Array<TaskProgressReportPublic>);

export type TasksGetTaskAuditData = {
    taskId: string;
};

export type TasksGetTaskAuditResponse = (Array<AuditLogPublic>);

export type TasksCheckConflictsData = {
    taskId: string;
};

export type TasksCheckConflictsResponse = ({
    [key: string]: unknown;
});

export type UsersReadUserByEmailData = {
    email: string;
};

export type UsersReadUserByEmailResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);