// This file is auto-generated by @hey-api/openapi-ts

export type AccountMembershipPublic = {
    company_id: string;
    company_name: string;
    role_id: string;
    role_name: string;
    role_display_name: string;
    role_level: number;
    is_primary: boolean;
};

export type AccountProfilePublic = {
    user_id: string;
    email: string;
    full_name: (string | null);
    memberships: Array<AccountMembershipPublic>;
};

export type AuditLogPublic = {
    id: string;
    actor_id: string;
    action: string;
    entity_type: string;
    entity_id: string;
    old_value: (unknown | null);
    new_value: (unknown | null);
    created_at: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CompanyCreate = {
    name: string;
    slug: string;
};

export type CompanyPublic = {
    id: string;
    name: string;
    slug: string;
    is_active: boolean;
};

export type CompanyUpdate = {
    name?: (string | null);
    is_active?: (boolean | null);
};

export type DepartmentCreate = {
    name: string;
    parent_id?: (string | null);
    dept_type?: (string | null);
};

export type DepartmentPublic = {
    id: string;
    company_id: string;
    parent_id: (string | null);
    name: string;
    dept_type: (string | null);
    is_active: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LogoutRequest = {
    refresh_token?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    name: string;
    code: string;
    description?: (string | null);
    start_date: string;
    end_date: string;
    status?: string;
    department_id?: (string | null);
};

export type ProjectPublic = {
    name: string;
    code: string;
    description?: (string | null);
    start_date: string;
    end_date: string;
    status?: string;
    id: string;
    company_id: string;
    department_id: (string | null);
    pm_id: string;
    created_at: string;
    updated_at: string;
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    name?: (string | null);
    description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    status?: (string | null);
    pm_id?: (string | null);
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

/**
 * Roles are DATA, not code.
 * System roles (is_system=True) are seeded and cannot be deleted.
 * Custom roles are created by admin via UI.
 */
export type Role = {
    id?: string;
    company_id: string;
    name: string;
    display_name: string;
    level?: number;
    is_system?: boolean;
    description?: (string | null);
    policy_doc?: ({
    [key: string]: unknown;
} | null);
    created_at?: string;
};

export type RoleCreate = {
    name: string;
    display_name: string;
    level?: number;
    description?: (string | null);
    policy_doc?: ({
    [key: string]: unknown;
} | null);
};

export type RoleDependencyCreate = {
    company_id: string;
    from_role_id: string;
    to_role_id: string;
    relation_type: 'REPORTS_TO' | 'PEERS_WITH' | 'REQUIRES_APPROVAL_FROM';
};

export type relation_type = 'REPORTS_TO' | 'PEERS_WITH' | 'REQUIRES_APPROVAL_FROM';

export type RoleDependencyPublic = {
    id: string;
    company_id: string;
    from_role_id: string;
    from_role_name: string;
    to_role_id: string;
    to_role_name: string;
    relation_type: string;
    is_active: boolean;
    created_at: string;
};

export type TaskChecklistCreate = {
    content: string;
};

export type TaskChecklistPublic = {
    id: string;
    task_id: string;
    content: string;
    is_completed: boolean;
    completed_by: (string | null);
    completed_at: (string | null);
    created_at: string;
};

export type TaskChecklistUpdate = {
    is_completed: boolean;
};

export type TaskCommentApprovalUpdate = {
    approval_status: 'APPROVED' | 'REJECTED';
};

export type approval_status = 'APPROVED' | 'REJECTED';

export type TaskCommentCreate = {
    content: string;
    comment_type?: string;
    requested_end_time?: (string | null);
    approval_status?: ('PENDING' | 'APPROVED' | 'REJECTED' | null);
};

export type TaskCommentPublic = {
    content: string;
    comment_type?: string;
    id: string;
    task_id: string;
    author_id: string;
    created_at: string;
    is_edited: boolean;
    requested_end_time: (string | null);
    approval_status: (string | null);
};

export type TaskCreate = {
    name: string;
    description?: (string | null);
    priority?: string;
    start_time: string;
    end_time: string;
    project_id: string;
    parent_id?: (string | null);
    assignee_id: string;
};

export type TaskDependencyCreate = {
    blocking_task_id: string;
    dependent_task_id: string;
    dependency_type?: 'FS' | 'SS' | 'FF' | 'SF';
    lag_hours?: number;
};

export type dependency_type = 'FS' | 'SS' | 'FF' | 'SF';

export type TaskLevelConfigCreate = {
    level: number;
    label: string;
    requires_proof?: boolean;
    can_have_children?: boolean;
    max_children?: (number | null);
    assignable_role_ids?: (Array<(string)> | null);
};

export type TaskLevelConfigPublic = {
    id: string;
    project_id: string;
    level: number;
    label: string;
    requires_proof: boolean;
    can_have_children: boolean;
    max_children: (number | null);
};

export type TaskProofCreate = {
    file_url: string;
    file_type?: string;
    note?: (string | null);
    gps_lat?: (number | null);
    gps_lng?: (number | null);
    captured_at?: (string | null);
    device_info?: (string | null);
};

export type TaskProofPublic = {
    id: string;
    task_id: string;
    uploader_id: string;
    file_url: string;
    file_type: string;
    note: (string | null);
    gps_lat: (number | null);
    gps_lng: (number | null);
    review_status: string;
    reviewer_id: (string | null);
    uploaded_at: string;
};

export type TaskPublic = {
    name: string;
    description?: (string | null);
    priority?: string;
    start_time: string;
    end_time: string;
    id: string;
    project_id: string;
    parent_id: (string | null);
    level: number;
    status: string;
    computed_status?: (string | null);
    assignor_id: string;
    assignee_id: string;
    actual_end_time: (string | null);
    is_on_critical_path: boolean;
    created_at: string;
    updated_at: string;
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskStatusUpdate = {
    status: string;
    note?: (string | null);
};

export type TaskUpdate = {
    name?: (string | null);
    description?: (string | null);
    priority?: (string | null);
    start_time?: (string | null);
    end_time?: (string | null);
    assignee_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
    refresh_token?: (string | null);
    session_id?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCompanyRoleCreate = {
    user_id: string;
    company_id: string;
    role_id: string;
    is_primary?: boolean;
};

export type UserCompanyRolePublic = {
    id: string;
    user_id: string;
    company_id: string;
    role_id: string;
    role_name: string;
    role_display_name: string;
    company_name: string;
    is_primary: boolean;
    assigned_at: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    department_id?: (string | null);
    job_title?: (string | null);
    availability_status?: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type DashboardOverviewData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardOverviewResponse = ({
    [key: string]: unknown;
});

export type DashboardProjectStatsData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardProjectStatsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardUserWorkloadData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardUserWorkloadResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardLeaderboardData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardLeaderboardResponse = (Array<{
    [key: string]: unknown;
}>);

export type DashboardOverdueReportData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardOverdueReportResponse = ({
    [key: string]: unknown;
});

export type DashboardTaskCalendarData = {
    departmentId?: (string | null);
    projectId?: (string | null);
};

export type DashboardTaskCalendarResponse = (Array<{
    [key: string]: unknown;
}>);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRefreshAccessTokenData = {
    requestBody: RefreshTokenRequest;
};

export type LoginRefreshAccessTokenResponse = (Token);

export type LoginLogoutData = {
    requestBody: LogoutRequest;
};

export type LoginLogoutResponse = (Message);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsListProjectsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type ProjectsListProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsGetProjectData = {
    projectId: string;
};

export type ProjectsGetProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsUpsertLevelConfigData = {
    projectId: string;
    requestBody: TaskLevelConfigCreate;
};

export type ProjectsUpsertLevelConfigResponse = (TaskLevelConfigPublic);

export type ProjectsGetLevelConfigsData = {
    projectId: string;
};

export type ProjectsGetLevelConfigsResponse = (Array<TaskLevelConfigPublic>);

export type ProjectsGetMembersData = {
    projectId: string;
};

export type ProjectsGetMembersResponse = (Array<{
    [key: string]: unknown;
}>);

export type ProjectsAddMemberData = {
    projectId: string;
    roleId: string;
    userId: string;
};

export type ProjectsAddMemberResponse = (unknown);

export type RolesListRoleDependenciesData = {
    companyId: string;
    relationType?: (string | null);
};

export type RolesListRoleDependenciesResponse = (Array<RoleDependencyPublic>);

export type RolesListCompanyRolesData = {
    companyId: string;
};

export type RolesListCompanyRolesResponse = (Array<Role>);

export type RolesListCompaniesResponse = (Array<CompanyPublic>);

export type RolesCreateCompanyData = {
    requestBody: CompanyCreate;
};

export type RolesCreateCompanyResponse = (CompanyPublic);

export type RolesUpdateCompanyData = {
    companyId: string;
    requestBody: CompanyUpdate;
};

export type RolesUpdateCompanyResponse = (CompanyPublic);

export type RolesCreateDepartmentData = {
    companyId: string;
    requestBody: DepartmentCreate;
};

export type RolesCreateDepartmentResponse = (DepartmentPublic);

export type RolesListDepartmentsData = {
    companyId: string;
};

export type RolesListDepartmentsResponse = (Array<DepartmentPublic>);

export type RolesCreateRoleData = {
    companyId: string;
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (Role);

export type RolesCreateRoleDependencyData = {
    requestBody: RoleDependencyCreate;
};

export type RolesCreateRoleDependencyResponse = (RoleDependencyPublic);

export type RolesAssignUserCompanyRoleData = {
    requestBody: UserCompanyRoleCreate;
};

export type RolesAssignUserCompanyRoleResponse = (UserCompanyRolePublic);

export type RolesListUserCompanyRolesData = {
    userId: string;
};

export type RolesListUserCompanyRolesResponse = (Array<UserCompanyRolePublic>);

export type RolesMyAccountProfileResponse = (AccountProfilePublic);

export type TasksCreateRootTaskData = {
    projectId: string;
    requestBody: TaskCreate;
};

export type TasksCreateRootTaskResponse = (TaskPublic);

export type TasksListProjectTasksData = {
    assigneeId?: (string | null);
    limit?: number;
    parentId?: (string | null);
    projectId: string;
    skip?: number;
};

export type TasksListProjectTasksResponse = (TasksPublic);

export type TasksCreateChildTaskData = {
    parentId: string;
    requestBody: TaskCreate;
};

export type TasksCreateChildTaskResponse = (TaskPublic);

export type TasksGetTaskData = {
    taskId: string;
};

export type TasksGetTaskResponse = (TaskPublic);

export type TasksUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    taskId: string;
};

export type TasksDeleteTaskResponse = (void);

export type TasksMyDashboardResponse = ({
    [key: string]: unknown;
});

export type TasksUpdateTaskStatusData = {
    requestBody: TaskStatusUpdate;
    taskId: string;
};

export type TasksUpdateTaskStatusResponse = (TaskPublic);

export type TasksCloneTaskData = {
    newAssigneeId?: (string | null);
    taskId: string;
};

export type TasksCloneTaskResponse = (TaskPublic);

export type TasksAddCommentData = {
    requestBody: TaskCommentCreate;
    taskId: string;
};

export type TasksAddCommentResponse = (TaskCommentPublic);

export type TasksListCommentsData = {
    taskId: string;
};

export type TasksListCommentsResponse = (Array<TaskCommentPublic>);

export type TasksApproveDelayRequestData = {
    commentId: string;
    requestBody: TaskCommentApprovalUpdate;
    taskId: string;
};

export type TasksApproveDelayRequestResponse = (TaskCommentPublic);

export type TasksUploadProofData = {
    requestBody: TaskProofCreate;
    taskId: string;
};

export type TasksUploadProofResponse = (TaskProofPublic);

export type TasksListProofsData = {
    taskId: string;
};

export type TasksListProofsResponse = (Array<TaskProofPublic>);

export type TasksReviewProofData = {
    proofId: string;
    reviewNote?: (string | null);
    reviewStatus: string;
    taskId: string;
};

export type TasksReviewProofResponse = (TaskProofPublic);

export type TasksAddDependencyData = {
    requestBody: TaskDependencyCreate;
    taskId: string;
};

export type TasksAddDependencyResponse = (unknown);

export type TasksAddChecklistItemData = {
    requestBody: TaskChecklistCreate;
    taskId: string;
};

export type TasksAddChecklistItemResponse = (TaskChecklistPublic);

export type TasksListChecklistItemsData = {
    taskId: string;
};

export type TasksListChecklistItemsResponse = (Array<TaskChecklistPublic>);

export type TasksUpdateChecklistItemData = {
    checklistId: string;
    requestBody: TaskChecklistUpdate;
    taskId: string;
};

export type TasksUpdateChecklistItemResponse = (TaskChecklistPublic);

export type TasksGetTaskAuditData = {
    taskId: string;
};

export type TasksGetTaskAuditResponse = (Array<AuditLogPublic>);

export type TasksCheckConflictsData = {
    taskId: string;
};

export type TasksCheckConflictsResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);