"""add_quotation_module

Revision ID: 5edf2c43c5c3
Revises: 0004_add_task_progress_weight
Create Date: 2026-04-22 12:27:59.519077

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5edf2c43c5c3'
down_revision = '0004_add_task_progress_weight'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation',
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('client_company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('client_contact_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('client_contact_phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('equipment_category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('quote_number', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('current_stage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('site_survey_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('sales_owner_id', sa.Uuid(), nullable=False),
    sa.Column('technical_owner_id', sa.Uuid(), nullable=True),
    sa.Column('procurement_owner_id', sa.Uuid(), nullable=True),
    sa.Column('price_coefficient', sa.Float(), nullable=True),
    sa.Column('total_cost_price', sa.Float(), nullable=True),
    sa.Column('total_sale_price', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('sent_to_client_at', sa.DateTime(), nullable=True),
    sa.Column('client_response_deadline', sa.Date(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('lost_reason_category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('lost_reason_detail', sa.Text(), nullable=True),
    sa.Column('won_project_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['procurement_owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sales_owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['technical_owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['won_project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_company_id'), 'quotation', ['company_id'], unique=False)
    op.create_index(op.f('ix_quotation_quote_number'), 'quotation', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotation_sales_owner_id'), 'quotation', ['sales_owner_id'], unique=False)
    op.create_table('quotationattachment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('stage_uploaded', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotationattachment_quotation_id'), 'quotationattachment', ['quotation_id'], unique=False)
    op.create_table('quotationlineitem',
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('cost_unit_price', sa.Float(), nullable=True),
    sa.Column('cost_total', sa.Float(), nullable=True),
    sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('supplier_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('procurement_note', sa.Text(), nullable=True),
    sa.Column('sale_unit_price', sa.Float(), nullable=True),
    sa.Column('sale_total', sa.Float(), nullable=True),
    sa.Column('created_by_role', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotationlineitem_quotation_id'), 'quotationlineitem', ['quotation_id'], unique=False)
    op.create_table('quotationnegotiationlog',
    sa.Column('contact_date', sa.Date(), nullable=False),
    sa.Column('contact_method', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('client_feedback', sa.Text(), nullable=True),
    sa.Column('requested_changes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('logged_by', sa.Uuid(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['logged_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotationnegotiationlog_quotation_id'), 'quotationnegotiationlog', ['quotation_id'], unique=False)
    op.create_table('quotationstagetransition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('to_stage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotationstagetransition_quotation_id'), 'quotationstagetransition', ['quotation_id'], unique=False)
    op.create_table('quotationversion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotationversion_quotation_id'), 'quotationversion', ['quotation_id'], unique=False)
    op.create_unique_constraint(None, 'chatmember', ['room_id', 'user_id'])
    op.drop_index(op.f('ix_notification_user_is_read'), table_name='notification')
    op.drop_constraint(op.f('notification_user_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_project_chat_room_id_chatroom'), 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'chatroom', ['chat_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_chat_room_id_chatroom'), 'project', 'chatroom', ['chat_room_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_user_id_fkey'), 'notification', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notification_user_is_read'), 'notification', ['user_id', 'is_read'], unique=False)
    op.drop_constraint(None, 'chatmember', type_='unique')
    op.drop_index(op.f('ix_quotationversion_quotation_id'), table_name='quotationversion')
    op.drop_table('quotationversion')
    op.drop_index(op.f('ix_quotationstagetransition_quotation_id'), table_name='quotationstagetransition')
    op.drop_table('quotationstagetransition')
    op.drop_index(op.f('ix_quotationnegotiationlog_quotation_id'), table_name='quotationnegotiationlog')
    op.drop_table('quotationnegotiationlog')
    op.drop_index(op.f('ix_quotationlineitem_quotation_id'), table_name='quotationlineitem')
    op.drop_table('quotationlineitem')
    op.drop_index(op.f('ix_quotationattachment_quotation_id'), table_name='quotationattachment')
    op.drop_table('quotationattachment')
    op.drop_index(op.f('ix_quotation_sales_owner_id'), table_name='quotation')
    op.drop_index(op.f('ix_quotation_quote_number'), table_name='quotation')
    op.drop_index(op.f('ix_quotation_company_id'), table_name='quotation')
    op.drop_table('quotation')
    # ### end Alembic commands ###
