/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReportsRouteImport } from './routes/_layout/reports'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutCompanyRouteImport } from './routes/_layout/company'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutTasksIndexRouteImport } from './routes/_layout/tasks.index'
import { Route as LayoutQuotationsIndexRouteImport } from './routes/_layout/quotations.index'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects.index'
import { Route as LayoutContractsIndexRouteImport } from './routes/_layout/contracts.index'
import { Route as LayoutTasksTaskIdRouteImport } from './routes/_layout/tasks.$taskId'
import { Route as LayoutQuotationsReportsRouteImport } from './routes/_layout/quotations.reports'
import { Route as LayoutQuotationsNewRouteImport } from './routes/_layout/quotations.new'
import { Route as LayoutQuotationsQuotationIdRouteImport } from './routes/_layout/quotations.$quotationId'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout/projects.$projectId'
import { Route as LayoutContractsNewRouteImport } from './routes/_layout/contracts.new'
import { Route as LayoutContractsContractIdRouteImport } from './routes/_layout/contracts.$contractId'
import { Route as LayoutDashboardPersonnelUserIdRouteImport } from './routes/_layout/dashboard.personnel.$userId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportsRoute = LayoutReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompanyRoute = LayoutCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksIndexRoute = LayoutTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuotationsIndexRoute = LayoutQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContractsIndexRoute = LayoutContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksTaskIdRoute = LayoutTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuotationsReportsRoute = LayoutQuotationsReportsRouteImport.update({
  id: '/quotations/reports',
  path: '/quotations/reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuotationsNewRoute = LayoutQuotationsNewRouteImport.update({
  id: '/quotations/new',
  path: '/quotations/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuotationsQuotationIdRoute =
  LayoutQuotationsQuotationIdRouteImport.update({
    id: '/quotations/$quotationId',
    path: '/quotations/$quotationId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContractsNewRoute = LayoutContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContractsContractIdRoute =
  LayoutContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDashboardPersonnelUserIdRoute =
  LayoutDashboardPersonnelUserIdRouteImport.update({
    id: '/dashboard/personnel/$userId',
    path: '/dashboard/personnel/$userId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRoute
  '/company': typeof LayoutCompanyRoute
  '/items': typeof LayoutItemsRoute
  '/reports': typeof LayoutReportsRoute
  '/settings': typeof LayoutSettingsRoute
  '/contracts/$contractId': typeof LayoutContractsContractIdRoute
  '/contracts/new': typeof LayoutContractsNewRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/quotations/$quotationId': typeof LayoutQuotationsQuotationIdRoute
  '/quotations/new': typeof LayoutQuotationsNewRoute
  '/quotations/reports': typeof LayoutQuotationsReportsRoute
  '/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/contracts/': typeof LayoutContractsIndexRoute
  '/projects/': typeof LayoutProjectsIndexRoute
  '/quotations/': typeof LayoutQuotationsIndexRoute
  '/tasks/': typeof LayoutTasksIndexRoute
  '/dashboard/personnel/$userId': typeof LayoutDashboardPersonnelUserIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRoute
  '/company': typeof LayoutCompanyRoute
  '/items': typeof LayoutItemsRoute
  '/reports': typeof LayoutReportsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/contracts/$contractId': typeof LayoutContractsContractIdRoute
  '/contracts/new': typeof LayoutContractsNewRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/quotations/$quotationId': typeof LayoutQuotationsQuotationIdRoute
  '/quotations/new': typeof LayoutQuotationsNewRoute
  '/quotations/reports': typeof LayoutQuotationsReportsRoute
  '/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/contracts': typeof LayoutContractsIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/quotations': typeof LayoutQuotationsIndexRoute
  '/tasks': typeof LayoutTasksIndexRoute
  '/dashboard/personnel/$userId': typeof LayoutDashboardPersonnelUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/company': typeof LayoutCompanyRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/reports': typeof LayoutReportsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/contracts/$contractId': typeof LayoutContractsContractIdRoute
  '/_layout/contracts/new': typeof LayoutContractsNewRoute
  '/_layout/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/_layout/quotations/$quotationId': typeof LayoutQuotationsQuotationIdRoute
  '/_layout/quotations/new': typeof LayoutQuotationsNewRoute
  '/_layout/quotations/reports': typeof LayoutQuotationsReportsRoute
  '/_layout/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/_layout/contracts/': typeof LayoutContractsIndexRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/quotations/': typeof LayoutQuotationsIndexRoute
  '/_layout/tasks/': typeof LayoutTasksIndexRoute
  '/_layout/dashboard/personnel/$userId': typeof LayoutDashboardPersonnelUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/company'
    | '/items'
    | '/reports'
    | '/settings'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/projects/$projectId'
    | '/quotations/$quotationId'
    | '/quotations/new'
    | '/quotations/reports'
    | '/tasks/$taskId'
    | '/contracts/'
    | '/projects/'
    | '/quotations/'
    | '/tasks/'
    | '/dashboard/personnel/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/company'
    | '/items'
    | '/reports'
    | '/settings'
    | '/'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/projects/$projectId'
    | '/quotations/$quotationId'
    | '/quotations/new'
    | '/quotations/reports'
    | '/tasks/$taskId'
    | '/contracts'
    | '/projects'
    | '/quotations'
    | '/tasks'
    | '/dashboard/personnel/$userId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/chat'
    | '/_layout/company'
    | '/_layout/items'
    | '/_layout/reports'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/contracts/$contractId'
    | '/_layout/contracts/new'
    | '/_layout/projects/$projectId'
    | '/_layout/quotations/$quotationId'
    | '/_layout/quotations/new'
    | '/_layout/quotations/reports'
    | '/_layout/tasks/$taskId'
    | '/_layout/contracts/'
    | '/_layout/projects/'
    | '/_layout/quotations/'
    | '/_layout/tasks/'
    | '/_layout/dashboard/personnel/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reports': {
      id: '/_layout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof LayoutReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/company': {
      id: '/_layout/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof LayoutCompanyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/': {
      id: '/_layout/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof LayoutTasksIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quotations/': {
      id: '/_layout/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof LayoutQuotationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contracts/': {
      id: '/_layout/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof LayoutContractsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/$taskId': {
      id: '/_layout/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof LayoutTasksTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quotations/reports': {
      id: '/_layout/quotations/reports'
      path: '/quotations/reports'
      fullPath: '/quotations/reports'
      preLoaderRoute: typeof LayoutQuotationsReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quotations/new': {
      id: '/_layout/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof LayoutQuotationsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quotations/$quotationId': {
      id: '/_layout/quotations/$quotationId'
      path: '/quotations/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof LayoutQuotationsQuotationIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId': {
      id: '/_layout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contracts/new': {
      id: '/_layout/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof LayoutContractsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contracts/$contractId': {
      id: '/_layout/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof LayoutContractsContractIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/personnel/$userId': {
      id: '/_layout/dashboard/personnel/$userId'
      path: '/dashboard/personnel/$userId'
      fullPath: '/dashboard/personnel/$userId'
      preLoaderRoute: typeof LayoutDashboardPersonnelUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutCompanyRoute: typeof LayoutCompanyRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutReportsRoute: typeof LayoutReportsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutContractsContractIdRoute: typeof LayoutContractsContractIdRoute
  LayoutContractsNewRoute: typeof LayoutContractsNewRoute
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRoute
  LayoutQuotationsQuotationIdRoute: typeof LayoutQuotationsQuotationIdRoute
  LayoutQuotationsNewRoute: typeof LayoutQuotationsNewRoute
  LayoutQuotationsReportsRoute: typeof LayoutQuotationsReportsRoute
  LayoutTasksTaskIdRoute: typeof LayoutTasksTaskIdRoute
  LayoutContractsIndexRoute: typeof LayoutContractsIndexRoute
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
  LayoutQuotationsIndexRoute: typeof LayoutQuotationsIndexRoute
  LayoutTasksIndexRoute: typeof LayoutTasksIndexRoute
  LayoutDashboardPersonnelUserIdRoute: typeof LayoutDashboardPersonnelUserIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutCompanyRoute: LayoutCompanyRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutReportsRoute: LayoutReportsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutContractsContractIdRoute: LayoutContractsContractIdRoute,
  LayoutContractsNewRoute: LayoutContractsNewRoute,
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRoute,
  LayoutQuotationsQuotationIdRoute: LayoutQuotationsQuotationIdRoute,
  LayoutQuotationsNewRoute: LayoutQuotationsNewRoute,
  LayoutQuotationsReportsRoute: LayoutQuotationsReportsRoute,
  LayoutTasksTaskIdRoute: LayoutTasksTaskIdRoute,
  LayoutContractsIndexRoute: LayoutContractsIndexRoute,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
  LayoutQuotationsIndexRoute: LayoutQuotationsIndexRoute,
  LayoutTasksIndexRoute: LayoutTasksIndexRoute,
  LayoutDashboardPersonnelUserIdRoute: LayoutDashboardPersonnelUserIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
