/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutYearSummaryRouteImport } from './routes/_layout/year-summary'
import { Route as LayoutStaffRouteImport } from './routes/_layout/staff'
import { Route as LayoutSkillRequestsRouteImport } from './routes/_layout/skill-requests'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReportsRouteImport } from './routes/_layout/reports'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutProductivityRouteImport } from './routes/_layout/productivity'
import { Route as LayoutOverviewDemoRouteImport } from './routes/_layout/overview-demo'
import { Route as LayoutMapRouteImport } from './routes/_layout/map'
import { Route as LayoutLeaveRouteImport } from './routes/_layout/leave'
import { Route as LayoutKpiRouteImport } from './routes/_layout/kpi'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutHelpRouteImport } from './routes/_layout/help'
import { Route as LayoutGanttRouteImport } from './routes/_layout/gantt'
import { Route as LayoutDispatchRouteImport } from './routes/_layout/dispatch'
import { Route as LayoutCompanyRouteImport } from './routes/_layout/company'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutAttendanceConfigRouteImport } from './routes/_layout/attendance-config'
import { Route as LayoutAttendanceRouteImport } from './routes/_layout/attendance'
import { Route as LayoutApprovalsRouteImport } from './routes/_layout/approvals'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutTasksIndexRouteImport } from './routes/_layout/tasks.index'
import { Route as LayoutQuotationsIndexRouteImport } from './routes/_layout/quotations.index'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects.index'
import { Route as LayoutIncidentsIndexRouteImport } from './routes/_layout/incidents.index'
import { Route as LayoutContractsIndexRouteImport } from './routes/_layout/contracts.index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin.index'
import { Route as LayoutTasksTaskIdRouteImport } from './routes/_layout/tasks.$taskId'
import { Route as LayoutQuotationsReportsRouteImport } from './routes/_layout/quotations.reports'
import { Route as LayoutQuotationsNewRouteImport } from './routes/_layout/quotations.new'
import { Route as LayoutQuotationsQuotationIdRouteImport } from './routes/_layout/quotations.$quotationId'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout/projects.$projectId'
import { Route as LayoutContractsNewRouteImport } from './routes/_layout/contracts.new'
import { Route as LayoutContractsContractIdRouteImport } from './routes/_layout/contracts.$contractId'
import { Route as LayoutAdminOverviewRouteImport } from './routes/_layout/admin.overview'
import { Route as LayoutAdminOrganizationRouteImport } from './routes/_layout/admin.organization'
import { Route as LayoutAdminCompaniesRouteImport } from './routes/_layout/admin.companies'
import { Route as LayoutAdminActivityRouteImport } from './routes/_layout/admin.activity'
import { Route as LayoutAdminUsersIndexRouteImport } from './routes/_layout/admin.users.index'
import { Route as LayoutDashboardPersonnelUserIdRouteImport } from './routes/_layout/dashboard.personnel.$userId'
import { Route as LayoutAdminUsersUserIdRouteImport } from './routes/_layout/admin.users.$userId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutYearSummaryRoute = LayoutYearSummaryRouteImport.update({
  id: '/year-summary',
  path: '/year-summary',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStaffRoute = LayoutStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillRequestsRoute = LayoutSkillRequestsRouteImport.update({
  id: '/skill-requests',
  path: '/skill-requests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportsRoute = LayoutReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductivityRoute = LayoutProductivityRouteImport.update({
  id: '/productivity',
  path: '/productivity',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOverviewDemoRoute = LayoutOverviewDemoRouteImport.update({
  id: '/overview-demo',
  path: '/overview-demo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMapRoute = LayoutMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeaveRoute = LayoutLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKpiRoute = LayoutKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHelpRoute = LayoutHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGanttRoute = LayoutGanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDispatchRoute = LayoutDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompanyRoute = LayoutCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAttendanceConfigRoute = LayoutAttendanceConfigRouteImport.update({
  id: '/attendance-config',
  path: '/attendance-config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAttendanceRoute = LayoutAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApprovalsRoute = LayoutApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksIndexRoute = LayoutTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuotationsIndexRoute = LayoutQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIncidentsIndexRoute = LayoutIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContractsIndexRoute = LayoutContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutTasksTaskIdRoute = LayoutTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuotationsReportsRoute = LayoutQuotationsReportsRouteImport.update({
  id: '/quotations/reports',
  path: '/quotations/reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuotationsNewRoute = LayoutQuotationsNewRouteImport.update({
  id: '/quotations/new',
  path: '/quotations/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuotationsQuotationIdRoute =
  LayoutQuotationsQuotationIdRouteImport.update({
    id: '/quotations/$quotationId',
    path: '/quotations/$quotationId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContractsNewRoute = LayoutContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContractsContractIdRoute =
  LayoutContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminOverviewRoute = LayoutAdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminOrganizationRoute = LayoutAdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminCompaniesRoute = LayoutAdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminActivityRoute = LayoutAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminUsersIndexRoute = LayoutAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutDashboardPersonnelUserIdRoute =
  LayoutDashboardPersonnelUserIdRouteImport.update({
    id: '/dashboard/personnel/$userId',
    path: '/dashboard/personnel/$userId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminUsersUserIdRoute = LayoutAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/approvals': typeof LayoutApprovalsRoute
  '/attendance': typeof LayoutAttendanceRoute
  '/attendance-config': typeof LayoutAttendanceConfigRoute
  '/chat': typeof LayoutChatRoute
  '/company': typeof LayoutCompanyRoute
  '/dispatch': typeof LayoutDispatchRoute
  '/gantt': typeof LayoutGanttRoute
  '/help': typeof LayoutHelpRoute
  '/items': typeof LayoutItemsRoute
  '/kpi': typeof LayoutKpiRoute
  '/leave': typeof LayoutLeaveRoute
  '/map': typeof LayoutMapRoute
  '/overview-demo': typeof LayoutOverviewDemoRoute
  '/productivity': typeof LayoutProductivityRoute
  '/profile': typeof LayoutProfileRoute
  '/reports': typeof LayoutReportsRoute
  '/settings': typeof LayoutSettingsRoute
  '/skill-requests': typeof LayoutSkillRequestsRoute
  '/staff': typeof LayoutStaffRoute
  '/year-summary': typeof LayoutYearSummaryRoute
  '/admin/activity': typeof LayoutAdminActivityRoute
  '/admin/companies': typeof LayoutAdminCompaniesRoute
  '/admin/organization': typeof LayoutAdminOrganizationRoute
  '/admin/overview': typeof LayoutAdminOverviewRoute
  '/contracts/$contractId': typeof LayoutContractsContractIdRoute
  '/contracts/new': typeof LayoutContractsNewRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/quotations/$quotationId': typeof LayoutQuotationsQuotationIdRoute
  '/quotations/new': typeof LayoutQuotationsNewRoute
  '/quotations/reports': typeof LayoutQuotationsReportsRoute
  '/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/contracts/': typeof LayoutContractsIndexRoute
  '/incidents/': typeof LayoutIncidentsIndexRoute
  '/projects/': typeof LayoutProjectsIndexRoute
  '/quotations/': typeof LayoutQuotationsIndexRoute
  '/tasks/': typeof LayoutTasksIndexRoute
  '/admin/users/$userId': typeof LayoutAdminUsersUserIdRoute
  '/dashboard/personnel/$userId': typeof LayoutDashboardPersonnelUserIdRoute
  '/admin/users/': typeof LayoutAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof LayoutApprovalsRoute
  '/attendance': typeof LayoutAttendanceRoute
  '/attendance-config': typeof LayoutAttendanceConfigRoute
  '/chat': typeof LayoutChatRoute
  '/company': typeof LayoutCompanyRoute
  '/dispatch': typeof LayoutDispatchRoute
  '/gantt': typeof LayoutGanttRoute
  '/help': typeof LayoutHelpRoute
  '/items': typeof LayoutItemsRoute
  '/kpi': typeof LayoutKpiRoute
  '/leave': typeof LayoutLeaveRoute
  '/map': typeof LayoutMapRoute
  '/overview-demo': typeof LayoutOverviewDemoRoute
  '/productivity': typeof LayoutProductivityRoute
  '/profile': typeof LayoutProfileRoute
  '/reports': typeof LayoutReportsRoute
  '/settings': typeof LayoutSettingsRoute
  '/skill-requests': typeof LayoutSkillRequestsRoute
  '/staff': typeof LayoutStaffRoute
  '/year-summary': typeof LayoutYearSummaryRoute
  '/': typeof LayoutIndexRoute
  '/admin/activity': typeof LayoutAdminActivityRoute
  '/admin/companies': typeof LayoutAdminCompaniesRoute
  '/admin/organization': typeof LayoutAdminOrganizationRoute
  '/admin/overview': typeof LayoutAdminOverviewRoute
  '/contracts/$contractId': typeof LayoutContractsContractIdRoute
  '/contracts/new': typeof LayoutContractsNewRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/quotations/$quotationId': typeof LayoutQuotationsQuotationIdRoute
  '/quotations/new': typeof LayoutQuotationsNewRoute
  '/quotations/reports': typeof LayoutQuotationsReportsRoute
  '/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/contracts': typeof LayoutContractsIndexRoute
  '/incidents': typeof LayoutIncidentsIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/quotations': typeof LayoutQuotationsIndexRoute
  '/tasks': typeof LayoutTasksIndexRoute
  '/admin/users/$userId': typeof LayoutAdminUsersUserIdRoute
  '/dashboard/personnel/$userId': typeof LayoutDashboardPersonnelUserIdRoute
  '/admin/users': typeof LayoutAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/approvals': typeof LayoutApprovalsRoute
  '/_layout/attendance': typeof LayoutAttendanceRoute
  '/_layout/attendance-config': typeof LayoutAttendanceConfigRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/company': typeof LayoutCompanyRoute
  '/_layout/dispatch': typeof LayoutDispatchRoute
  '/_layout/gantt': typeof LayoutGanttRoute
  '/_layout/help': typeof LayoutHelpRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/kpi': typeof LayoutKpiRoute
  '/_layout/leave': typeof LayoutLeaveRoute
  '/_layout/map': typeof LayoutMapRoute
  '/_layout/overview-demo': typeof LayoutOverviewDemoRoute
  '/_layout/productivity': typeof LayoutProductivityRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/reports': typeof LayoutReportsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/skill-requests': typeof LayoutSkillRequestsRoute
  '/_layout/staff': typeof LayoutStaffRoute
  '/_layout/year-summary': typeof LayoutYearSummaryRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/activity': typeof LayoutAdminActivityRoute
  '/_layout/admin/companies': typeof LayoutAdminCompaniesRoute
  '/_layout/admin/organization': typeof LayoutAdminOrganizationRoute
  '/_layout/admin/overview': typeof LayoutAdminOverviewRoute
  '/_layout/contracts/$contractId': typeof LayoutContractsContractIdRoute
  '/_layout/contracts/new': typeof LayoutContractsNewRoute
  '/_layout/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/_layout/quotations/$quotationId': typeof LayoutQuotationsQuotationIdRoute
  '/_layout/quotations/new': typeof LayoutQuotationsNewRoute
  '/_layout/quotations/reports': typeof LayoutQuotationsReportsRoute
  '/_layout/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/contracts/': typeof LayoutContractsIndexRoute
  '/_layout/incidents/': typeof LayoutIncidentsIndexRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/quotations/': typeof LayoutQuotationsIndexRoute
  '/_layout/tasks/': typeof LayoutTasksIndexRoute
  '/_layout/admin/users/$userId': typeof LayoutAdminUsersUserIdRoute
  '/_layout/dashboard/personnel/$userId': typeof LayoutDashboardPersonnelUserIdRoute
  '/_layout/admin/users/': typeof LayoutAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/approvals'
    | '/attendance'
    | '/attendance-config'
    | '/chat'
    | '/company'
    | '/dispatch'
    | '/gantt'
    | '/help'
    | '/items'
    | '/kpi'
    | '/leave'
    | '/map'
    | '/overview-demo'
    | '/productivity'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/skill-requests'
    | '/staff'
    | '/year-summary'
    | '/admin/activity'
    | '/admin/companies'
    | '/admin/organization'
    | '/admin/overview'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/projects/$projectId'
    | '/quotations/$quotationId'
    | '/quotations/new'
    | '/quotations/reports'
    | '/tasks/$taskId'
    | '/admin/'
    | '/contracts/'
    | '/incidents/'
    | '/projects/'
    | '/quotations/'
    | '/tasks/'
    | '/admin/users/$userId'
    | '/dashboard/personnel/$userId'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/approvals'
    | '/attendance'
    | '/attendance-config'
    | '/chat'
    | '/company'
    | '/dispatch'
    | '/gantt'
    | '/help'
    | '/items'
    | '/kpi'
    | '/leave'
    | '/map'
    | '/overview-demo'
    | '/productivity'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/skill-requests'
    | '/staff'
    | '/year-summary'
    | '/'
    | '/admin/activity'
    | '/admin/companies'
    | '/admin/organization'
    | '/admin/overview'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/projects/$projectId'
    | '/quotations/$quotationId'
    | '/quotations/new'
    | '/quotations/reports'
    | '/tasks/$taskId'
    | '/admin'
    | '/contracts'
    | '/incidents'
    | '/projects'
    | '/quotations'
    | '/tasks'
    | '/admin/users/$userId'
    | '/dashboard/personnel/$userId'
    | '/admin/users'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/approvals'
    | '/_layout/attendance'
    | '/_layout/attendance-config'
    | '/_layout/chat'
    | '/_layout/company'
    | '/_layout/dispatch'
    | '/_layout/gantt'
    | '/_layout/help'
    | '/_layout/items'
    | '/_layout/kpi'
    | '/_layout/leave'
    | '/_layout/map'
    | '/_layout/overview-demo'
    | '/_layout/productivity'
    | '/_layout/profile'
    | '/_layout/reports'
    | '/_layout/settings'
    | '/_layout/skill-requests'
    | '/_layout/staff'
    | '/_layout/year-summary'
    | '/_layout/'
    | '/_layout/admin/activity'
    | '/_layout/admin/companies'
    | '/_layout/admin/organization'
    | '/_layout/admin/overview'
    | '/_layout/contracts/$contractId'
    | '/_layout/contracts/new'
    | '/_layout/projects/$projectId'
    | '/_layout/quotations/$quotationId'
    | '/_layout/quotations/new'
    | '/_layout/quotations/reports'
    | '/_layout/tasks/$taskId'
    | '/_layout/admin/'
    | '/_layout/contracts/'
    | '/_layout/incidents/'
    | '/_layout/projects/'
    | '/_layout/quotations/'
    | '/_layout/tasks/'
    | '/_layout/admin/users/$userId'
    | '/_layout/dashboard/personnel/$userId'
    | '/_layout/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/year-summary': {
      id: '/_layout/year-summary'
      path: '/year-summary'
      fullPath: '/year-summary'
      preLoaderRoute: typeof LayoutYearSummaryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/staff': {
      id: '/_layout/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof LayoutStaffRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skill-requests': {
      id: '/_layout/skill-requests'
      path: '/skill-requests'
      fullPath: '/skill-requests'
      preLoaderRoute: typeof LayoutSkillRequestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reports': {
      id: '/_layout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof LayoutReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/productivity': {
      id: '/_layout/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof LayoutProductivityRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/overview-demo': {
      id: '/_layout/overview-demo'
      path: '/overview-demo'
      fullPath: '/overview-demo'
      preLoaderRoute: typeof LayoutOverviewDemoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/map': {
      id: '/_layout/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof LayoutMapRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leave': {
      id: '/_layout/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LayoutLeaveRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/kpi': {
      id: '/_layout/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof LayoutKpiRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/help': {
      id: '/_layout/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof LayoutHelpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/gantt': {
      id: '/_layout/gantt'
      path: '/gantt'
      fullPath: '/gantt'
      preLoaderRoute: typeof LayoutGanttRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dispatch': {
      id: '/_layout/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof LayoutDispatchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/company': {
      id: '/_layout/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof LayoutCompanyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/attendance-config': {
      id: '/_layout/attendance-config'
      path: '/attendance-config'
      fullPath: '/attendance-config'
      preLoaderRoute: typeof LayoutAttendanceConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/attendance': {
      id: '/_layout/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof LayoutAttendanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/approvals': {
      id: '/_layout/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof LayoutApprovalsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/': {
      id: '/_layout/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof LayoutTasksIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quotations/': {
      id: '/_layout/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof LayoutQuotationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/incidents/': {
      id: '/_layout/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof LayoutIncidentsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contracts/': {
      id: '/_layout/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof LayoutContractsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/tasks/$taskId': {
      id: '/_layout/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof LayoutTasksTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quotations/reports': {
      id: '/_layout/quotations/reports'
      path: '/quotations/reports'
      fullPath: '/quotations/reports'
      preLoaderRoute: typeof LayoutQuotationsReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quotations/new': {
      id: '/_layout/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof LayoutQuotationsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quotations/$quotationId': {
      id: '/_layout/quotations/$quotationId'
      path: '/quotations/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof LayoutQuotationsQuotationIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId': {
      id: '/_layout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contracts/new': {
      id: '/_layout/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof LayoutContractsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contracts/$contractId': {
      id: '/_layout/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof LayoutContractsContractIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/overview': {
      id: '/_layout/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof LayoutAdminOverviewRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/organization': {
      id: '/_layout/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof LayoutAdminOrganizationRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/companies': {
      id: '/_layout/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof LayoutAdminCompaniesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/activity': {
      id: '/_layout/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof LayoutAdminActivityRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/users/': {
      id: '/_layout/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof LayoutAdminUsersIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/dashboard/personnel/$userId': {
      id: '/_layout/dashboard/personnel/$userId'
      path: '/dashboard/personnel/$userId'
      fullPath: '/dashboard/personnel/$userId'
      preLoaderRoute: typeof LayoutDashboardPersonnelUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users/$userId': {
      id: '/_layout/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof LayoutAdminUsersUserIdRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminActivityRoute: typeof LayoutAdminActivityRoute
  LayoutAdminCompaniesRoute: typeof LayoutAdminCompaniesRoute
  LayoutAdminOrganizationRoute: typeof LayoutAdminOrganizationRoute
  LayoutAdminOverviewRoute: typeof LayoutAdminOverviewRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
  LayoutAdminUsersUserIdRoute: typeof LayoutAdminUsersUserIdRoute
  LayoutAdminUsersIndexRoute: typeof LayoutAdminUsersIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminActivityRoute: LayoutAdminActivityRoute,
  LayoutAdminCompaniesRoute: LayoutAdminCompaniesRoute,
  LayoutAdminOrganizationRoute: LayoutAdminOrganizationRoute,
  LayoutAdminOverviewRoute: LayoutAdminOverviewRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
  LayoutAdminUsersUserIdRoute: LayoutAdminUsersUserIdRoute,
  LayoutAdminUsersIndexRoute: LayoutAdminUsersIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutApprovalsRoute: typeof LayoutApprovalsRoute
  LayoutAttendanceRoute: typeof LayoutAttendanceRoute
  LayoutAttendanceConfigRoute: typeof LayoutAttendanceConfigRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutCompanyRoute: typeof LayoutCompanyRoute
  LayoutDispatchRoute: typeof LayoutDispatchRoute
  LayoutGanttRoute: typeof LayoutGanttRoute
  LayoutHelpRoute: typeof LayoutHelpRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutKpiRoute: typeof LayoutKpiRoute
  LayoutLeaveRoute: typeof LayoutLeaveRoute
  LayoutMapRoute: typeof LayoutMapRoute
  LayoutOverviewDemoRoute: typeof LayoutOverviewDemoRoute
  LayoutProductivityRoute: typeof LayoutProductivityRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutReportsRoute: typeof LayoutReportsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSkillRequestsRoute: typeof LayoutSkillRequestsRoute
  LayoutStaffRoute: typeof LayoutStaffRoute
  LayoutYearSummaryRoute: typeof LayoutYearSummaryRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutContractsContractIdRoute: typeof LayoutContractsContractIdRoute
  LayoutContractsNewRoute: typeof LayoutContractsNewRoute
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRoute
  LayoutQuotationsQuotationIdRoute: typeof LayoutQuotationsQuotationIdRoute
  LayoutQuotationsNewRoute: typeof LayoutQuotationsNewRoute
  LayoutQuotationsReportsRoute: typeof LayoutQuotationsReportsRoute
  LayoutTasksTaskIdRoute: typeof LayoutTasksTaskIdRoute
  LayoutContractsIndexRoute: typeof LayoutContractsIndexRoute
  LayoutIncidentsIndexRoute: typeof LayoutIncidentsIndexRoute
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
  LayoutQuotationsIndexRoute: typeof LayoutQuotationsIndexRoute
  LayoutTasksIndexRoute: typeof LayoutTasksIndexRoute
  LayoutDashboardPersonnelUserIdRoute: typeof LayoutDashboardPersonnelUserIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutApprovalsRoute: LayoutApprovalsRoute,
  LayoutAttendanceRoute: LayoutAttendanceRoute,
  LayoutAttendanceConfigRoute: LayoutAttendanceConfigRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutCompanyRoute: LayoutCompanyRoute,
  LayoutDispatchRoute: LayoutDispatchRoute,
  LayoutGanttRoute: LayoutGanttRoute,
  LayoutHelpRoute: LayoutHelpRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutKpiRoute: LayoutKpiRoute,
  LayoutLeaveRoute: LayoutLeaveRoute,
  LayoutMapRoute: LayoutMapRoute,
  LayoutOverviewDemoRoute: LayoutOverviewDemoRoute,
  LayoutProductivityRoute: LayoutProductivityRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutReportsRoute: LayoutReportsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSkillRequestsRoute: LayoutSkillRequestsRoute,
  LayoutStaffRoute: LayoutStaffRoute,
  LayoutYearSummaryRoute: LayoutYearSummaryRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutContractsContractIdRoute: LayoutContractsContractIdRoute,
  LayoutContractsNewRoute: LayoutContractsNewRoute,
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRoute,
  LayoutQuotationsQuotationIdRoute: LayoutQuotationsQuotationIdRoute,
  LayoutQuotationsNewRoute: LayoutQuotationsNewRoute,
  LayoutQuotationsReportsRoute: LayoutQuotationsReportsRoute,
  LayoutTasksTaskIdRoute: LayoutTasksTaskIdRoute,
  LayoutContractsIndexRoute: LayoutContractsIndexRoute,
  LayoutIncidentsIndexRoute: LayoutIncidentsIndexRoute,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
  LayoutQuotationsIndexRoute: LayoutQuotationsIndexRoute,
  LayoutTasksIndexRoute: LayoutTasksIndexRoute,
  LayoutDashboardPersonnelUserIdRoute: LayoutDashboardPersonnelUserIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
